CREATE PROCEDURE [dbo].[sp_ApagaLogBookAcaoTomada]
	@pACT_ID INT OUTPUT
AS
BEGIN
	DELETE FROM LB_ACOESTOMADAS_ARQUIVOS WHERE ACT_ID = @pACT_ID
	IF @@ERROR <> 0 BEGIN
		ROLLBACK TRANSACTION
		RAISERROR( 'Não foi possível excluir os arquivos desta ação.', 16, 1 )
		SELECT -1 AS SAIDA
		RETURN -1
	END

	DELETE FROM LB_ACOESTOMADAS WHERE ACT_ID = @pACT_ID
	IF @@ERROR <> 0 BEGIN
		ROLLBACK TRANSACTION
		RAISERROR( 'Não foi possível atualizar esta ação.', 16, 1 )
		SELECT -1 AS SAIDA
		RETURN -1
	END
	COMMIT TRANSACTION
	SELECT @pACT_ID AS SAIDA
	RETURN @pACT_ID
END


DROP PROCEDURE dbo.sp_CadDePara
