CREATE PROCEDURE [dbo].[sp_ApagaLogBookAcaoTomadaArquivos]
	@pACA_ID INT OUTPUT
AS
BEGIN
	DELETE FROM LB_ACOESTOMADAS_ARQUIVOS WHERE ACA_ID = @pACA_ID
	IF @@ERROR <> 0 BEGIN
		ROLLBACK TRANSACTION
		RAISERROR( 'Não foi possível excluir o arquivo.', 16, 1 )
		SELECT -1 AS SAIDA
		RETURN -1
	END
	COMMIT TRANSACTION
	SELECT @pACA_ID AS SAIDA
	RETURN @pACA_ID
END
