
CREATE PROCEDURE [dbo].[SP_CONSULTA_TAREFA]
@tpid  INT
AS
SELECT TP.TAREFA_ID, AG_TITULO AS DESCRICAO_TAREFA, TP.TP_DATAINICIAL, TP.TP_DATAFINAL, TP.PES_USERNAME, TP.TP_OBSERVACAO, TP.TAREFA_TIPO
FROM TAREFAS_PREVISTAS AS TP
LEFT JOIN AGENDAMENTO AS A ON A.AG_NUMERO = TP.TAREFA_ID
WHERE TP.TP_ID = @tpid
AND TAREFA_TIPO = 0
UNION
SELECT TP.TAREFA_ID, T.TAR_DESCRICAO AS DESCRICAO_TAREFA, TP.TP_DATAINICIAL, TP.TP_DATAFINAL, TP.PES_USERNAME, TP.TP_OBSERVACAO, TP.TAREFA_TIPO
FROM TAREFAS_PREVISTAS AS TP
LEFT JOIN TAREFAS AS T ON T.TAR_ID = TP.TAREFA_ID
WHERE TP.TP_ID = @tpid
AND TAREFA_TIPO = 1
