CREATE PROCEDURE [dbo].[SP_FAC_ATUALIZA_FABRICANTE]
@fabID		INTEGER,
@fabNome	VARCHAR(200)

AS

SET NOCOUNT ON

UPDATE FAC_FABRICANTE_TIPO_COMPONENTE SET FAB_NOME = UPPER ( @fabNome ) WHERE FAB_ID = @fabID

IF @@ERROR > 0
	RETURN -1 --erro ao atualizar
ELSE
	RETURN 1

