CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_CARACTERISTICA]
@carNome	VARCHAR(50),
@carDefinicao	VARCHAR(5000)

AS

SET NOCOUNT ON

DECLARE @tmp INTEGER

SELECT @tmp = CAR_ID FROM FAC_CARACTERISTICAS WHERE UPPER( @carNome ) = CAR_NOME

IF @@ROWCOUNT > 0
	RETURN @tmp
ELSE BEGIN

	INSERT INTO FAC_CARACTERISTICAS (CAR_NOME, CAR_DEFINICAO) VALUES ( UPPER( @carNome ), UPPER( @carDefinicao ) )

	IF @@ERROR > 0
		RETURN -1
	ELSE
		RETURN @@IDENTITY
END

