CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_REL_CARACTERISTICAS_FACILIDADES]
@carID		INTEGER,
@tpcID		INTEGER,
@facID		INTEGER,
@rcfIdentCaract	VARCHAR(255)

AS

SET NOCOUNT ON

SELECT FAC_ID FROM	FAC_FACILIDADES
	INNER JOIN FAC_COMPONENTES ON FAC_FACILIDADES.CPT_ID = FAC_COMPONENTES.CPT_ID
	INNER JOIN FAC_TIPO_COMPONENTE ON FAC_COMPONENTES.TPC_ID = FAC_TIPO_COMPONENTE.TPC_ID
	INNER JOIN FAC_REL_CARACTERISTICAS_TIPO ON FAC_TIPO_COMPONENTE. TPC_ID = FAC_REL_CARACTERISTICAS_TIPO.TPC_ID
WHERE FAC_REL_CARACTERISTICAS_TIPO.CAR_ID = @carID AND FAC_REL_CARACTERISTICAS_TIPO.TPC_ID = @tpcID AND FAC_FACILIDADES.FAC_ID = @facID

IF @@ROWCOUNT = 0
	RETURN -1 --o relacionamento não existe, logo esta característica não pertence a este tipo de equipamento
ELSE BEGIN
	INSERT INTO FAC_REL_CARACTERISTICAS_FACILIDADES (CAR_ID, TPC_ID, FAC_ID, RCF_IDENTIFICADOR_CARACTERISTICA) VALUES (@carID, @tpcID, @facID, @rcfIdentCaract)
	IF @@ERROR > 0
		RETURN -2 --erro de inserção
	ELSE
		RETURN 1 --OK
END



