CREATE PROCEDURE [dbo].[SP_TAREFAS_POR_PERIODO]
	@data  VARCHAR(10),
	@username VARCHAR(10)
AS

SELECT TP.TP_ID, TP.TAREFA_ID, A.AG_NUMERO AS ORDEM, 'Nº AS:'+CAST(A.AG_NUMERO AS VARCHAR) AS TIPO, CAST(A.AG_OBJETIVO AS VARCHAR(8000)) AS DESCRICAO_TAREFA,
	CONVERT(SMALLDATETIME, CAST(DAY(TP.TP_DATAINICIAL) AS VARCHAR)+'/'+CAST(MONTH(TP.TP_DATAINICIAL) AS VARCHAR)+'/'+CAST(YEAR(TP.TP_DATAINICIAL) AS VARCHAR), 103) AS TP_DATAINICIAL,
	CONVERT(SMALLDATETIME, CAST(DAY(TP.TP_DATAFINAL) AS VARCHAR)+'/'+CAST(MONTH(TP.TP_DATAFINAL) AS VARCHAR)+'/'+CAST(YEAR(TP.TP_DATAFINAL) AS VARCHAR), 103) AS TP_DATAFINAL,
	TP.PES_USERNAME, TP.TP_OBSERVACAO, TP.TAREFA_TIPO
FROM TAREFAS_PREVISTAS AS TP
LEFT JOIN AGENDAMENTO AS A ON A.AG_NUMERO = TP.TAREFA_ID
WHERE TP_DATAINICIAL <= DATEADD(DD, 13, CONVERT(DATETIME, @data, 103))
AND TP_DATAFINAL >= CONVERT(DATETIME, @data, 103)
AND TP.PES_USERNAME = @username
AND TAREFA_TIPO = 0
UNION
SELECT TP.TP_ID, TP.TAREFA_ID, 999999 AS ORDEM,  'TAR' AS TIPO, T.TAR_DESCRICAO AS DESCRICAO_TAREFA,
	CONVERT(SMALLDATETIME, CAST(DAY(TP.TP_DATAINICIAL) AS VARCHAR)+'/'+CAST(MONTH(TP.TP_DATAINICIAL) AS VARCHAR)+'/'+CAST(YEAR(TP.TP_DATAINICIAL) AS VARCHAR), 103) AS TP_DATAINICIAL,
	CONVERT(SMALLDATETIME, CAST(DAY(TP.TP_DATAFINAL) AS VARCHAR)+'/'+CAST(MONTH(TP.TP_DATAFINAL) AS VARCHAR)+'/'+CAST(YEAR(TP.TP_DATAFINAL) AS VARCHAR), 103) AS TP_DATAFINAL,
	TP.PES_USERNAME, TP.TP_OBSERVACAO, TP.TAREFA_TIPO
FROM TAREFAS_PREVISTAS AS TP
LEFT JOIN TAREFAS AS T ON T.TAR_ID = TP.TAREFA_ID
WHERE TP_DATAINICIAL <= DATEADD(DD, 13, CONVERT(DATETIME, @data, 103))
AND TP_DATAFINAL >= CONVERT(DATETIME, @data, 103)
AND TP.PES_USERNAME = @username
AND TAREFA_TIPO = 1
ORDER BY ORDEM, TP_DATAINICIAL
