//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailTeste.svcSislab {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcSislab.UsuariosSoap")]
    public interface UsuariosSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemUsuario", ReplyAction="*")]
        EmailTeste.svcSislab.ObtemUsuarioResponse ObtemUsuario(EmailTeste.svcSislab.ObtemUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name remetente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEmail", ReplyAction="*")]
        EmailTeste.svcSislab.EnviaEmailResponse EnviaEmail(EmailTeste.svcSislab.EnviaEmailRequest request);
        
        // CODEGEN: Generating message contract since element name smtpServer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEmailGenerico", ReplyAction="*")]
        EmailTeste.svcSislab.EnviaEmailGenericoResponse EnviaEmailGenerico(EmailTeste.svcSislab.EnviaEmailGenericoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemUsuario", Namespace="http://tempuri.org/", Order=0)]
        public EmailTeste.svcSislab.ObtemUsuarioRequestBody Body;
        
        public ObtemUsuarioRequest() {
        }
        
        public ObtemUsuarioRequest(EmailTeste.svcSislab.ObtemUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        public ObtemUsuarioRequestBody() {
        }
        
        public ObtemUsuarioRequestBody(string login, string dominio) {
            this.login = login;
            this.dominio = dominio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailTeste.svcSislab.ObtemUsuarioResponseBody Body;
        
        public ObtemUsuarioResponse() {
        }
        
        public ObtemUsuarioResponse(EmailTeste.svcSislab.ObtemUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtemUsuarioResult;
        
        public ObtemUsuarioResponseBody() {
        }
        
        public ObtemUsuarioResponseBody(string ObtemUsuarioResult) {
            this.ObtemUsuarioResult = ObtemUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmail", Namespace="http://tempuri.org/", Order=0)]
        public EmailTeste.svcSislab.EnviaEmailRequestBody Body;
        
        public EnviaEmailRequest() {
        }
        
        public EnviaEmailRequest(EmailTeste.svcSislab.EnviaEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string remetente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string assunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mensagem;
        
        public EnviaEmailRequestBody() {
        }
        
        public EnviaEmailRequestBody(string remetente, string destinatario, string assunto, string mensagem) {
            this.remetente = remetente;
            this.destinatario = destinatario;
            this.assunto = assunto;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailTeste.svcSislab.EnviaEmailResponseBody Body;
        
        public EnviaEmailResponse() {
        }
        
        public EnviaEmailResponse(EmailTeste.svcSislab.EnviaEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaEmailResult;
        
        public EnviaEmailResponseBody() {
        }
        
        public EnviaEmailResponseBody(string EnviaEmailResult) {
            this.EnviaEmailResult = EnviaEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailGenericoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmailGenerico", Namespace="http://tempuri.org/", Order=0)]
        public EmailTeste.svcSislab.EnviaEmailGenericoRequestBody Body;
        
        public EnviaEmailGenericoRequest() {
        }
        
        public EnviaEmailGenericoRequest(EmailTeste.svcSislab.EnviaEmailGenericoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailGenericoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smtpServer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroPorta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool habilitarSSL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string remetente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string assunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string mensagem;
        
        public EnviaEmailGenericoRequestBody() {
        }
        
        public EnviaEmailGenericoRequestBody(string smtpServer, string numeroPorta, bool habilitarSSL, string remetente, string senha, string destinatario, string assunto, string mensagem) {
            this.smtpServer = smtpServer;
            this.numeroPorta = numeroPorta;
            this.habilitarSSL = habilitarSSL;
            this.remetente = remetente;
            this.senha = senha;
            this.destinatario = destinatario;
            this.assunto = assunto;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailGenericoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmailGenericoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailTeste.svcSislab.EnviaEmailGenericoResponseBody Body;
        
        public EnviaEmailGenericoResponse() {
        }
        
        public EnviaEmailGenericoResponse(EmailTeste.svcSislab.EnviaEmailGenericoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailGenericoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaEmailGenericoResult;
        
        public EnviaEmailGenericoResponseBody() {
        }
        
        public EnviaEmailGenericoResponseBody(string EnviaEmailGenericoResult) {
            this.EnviaEmailGenericoResult = EnviaEmailGenericoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuariosSoapChannel : EmailTeste.svcSislab.UsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosSoapClient : System.ServiceModel.ClientBase<EmailTeste.svcSislab.UsuariosSoap>, EmailTeste.svcSislab.UsuariosSoap {
        
        public UsuariosSoapClient() {
        }
        
        public UsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailTeste.svcSislab.ObtemUsuarioResponse EmailTeste.svcSislab.UsuariosSoap.ObtemUsuario(EmailTeste.svcSislab.ObtemUsuarioRequest request) {
            return base.Channel.ObtemUsuario(request);
        }
        
        public string ObtemUsuario(string login, string dominio) {
            EmailTeste.svcSislab.ObtemUsuarioRequest inValue = new EmailTeste.svcSislab.ObtemUsuarioRequest();
            inValue.Body = new EmailTeste.svcSislab.ObtemUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.dominio = dominio;
            EmailTeste.svcSislab.ObtemUsuarioResponse retVal = ((EmailTeste.svcSislab.UsuariosSoap)(this)).ObtemUsuario(inValue);
            return retVal.Body.ObtemUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailTeste.svcSislab.EnviaEmailResponse EmailTeste.svcSislab.UsuariosSoap.EnviaEmail(EmailTeste.svcSislab.EnviaEmailRequest request) {
            return base.Channel.EnviaEmail(request);
        }
        
        public string EnviaEmail(string remetente, string destinatario, string assunto, string mensagem) {
            EmailTeste.svcSislab.EnviaEmailRequest inValue = new EmailTeste.svcSislab.EnviaEmailRequest();
            inValue.Body = new EmailTeste.svcSislab.EnviaEmailRequestBody();
            inValue.Body.remetente = remetente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            EmailTeste.svcSislab.EnviaEmailResponse retVal = ((EmailTeste.svcSislab.UsuariosSoap)(this)).EnviaEmail(inValue);
            return retVal.Body.EnviaEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmailTeste.svcSislab.EnviaEmailGenericoResponse EmailTeste.svcSislab.UsuariosSoap.EnviaEmailGenerico(EmailTeste.svcSislab.EnviaEmailGenericoRequest request) {
            return base.Channel.EnviaEmailGenerico(request);
        }
        
        public string EnviaEmailGenerico(string smtpServer, string numeroPorta, bool habilitarSSL, string remetente, string senha, string destinatario, string assunto, string mensagem) {
            EmailTeste.svcSislab.EnviaEmailGenericoRequest inValue = new EmailTeste.svcSislab.EnviaEmailGenericoRequest();
            inValue.Body = new EmailTeste.svcSislab.EnviaEmailGenericoRequestBody();
            inValue.Body.smtpServer = smtpServer;
            inValue.Body.numeroPorta = numeroPorta;
            inValue.Body.habilitarSSL = habilitarSSL;
            inValue.Body.remetente = remetente;
            inValue.Body.senha = senha;
            inValue.Body.destinatario = destinatario;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            EmailTeste.svcSislab.EnviaEmailGenericoResponse retVal = ((EmailTeste.svcSislab.UsuariosSoap)(this)).EnviaEmailGenerico(inValue);
            return retVal.Body.EnviaEmailGenericoResult;
        }
    }
}
