CREATE VIEW [dbo].[vw_circuitos]
AS
SELECT dbo.FAC_COMPONENTES.CPT_ID, 
    dbo.FAC_COMPONENTES.CPT_NOME, 
    dbo.FAC_CARACTERISTICAS.CAR_NOME, 
    dbo.FAC_TIPO_CIRCUITO.TPC_NOME, 
    dbo.FAC_CIRCUITO.CTO_NOME, 
    dbo.FAC_REL_CARACTERISTICAS_FACILIDADES.RCF_IDENTIFICADOR_CARACTERISTICA,
     dbo.FAC_FACILIDADES.FAC_ID
FROM dbo.FAC_REL_CARACTERISTICAS_FACILIDADES INNER JOIN
    dbo.FAC_COMPONENTES ON 
    dbo.FAC_REL_CARACTERISTICAS_FACILIDADES.TPC_ID = dbo.FAC_COMPONENTES.TPC_ID
     INNER JOIN
    dbo.FAC_REL_CARACTERISTICAS_TIPO ON 
    dbo.FAC_REL_CARACTERISTICAS_FACILIDADES.CAR_ID = dbo.FAC_REL_CARACTERISTICAS_TIPO.CAR_ID
     AND 
    dbo.FAC_REL_CARACTERISTICAS_FACILIDADES.TPC_ID = dbo.FAC_REL_CARACTERISTICAS_TIPO.TPC_ID
     INNER JOIN
    dbo.FAC_CARACTERISTICAS ON 
    dbo.FAC_REL_CARACTERISTICAS_TIPO.CAR_ID = dbo.FAC_CARACTERISTICAS.CAR_ID
     INNER JOIN
    dbo.FAC_FACILIDADES ON 
    dbo.FAC_COMPONENTES.CPT_ID = dbo.FAC_FACILIDADES.CPT_ID
     AND 
    dbo.FAC_REL_CARACTERISTICAS_FACILIDADES.FAC_ID = dbo.FAC_FACILIDADES.FAC_ID
     LEFT OUTER JOIN
    dbo.FAC_CIRCUITO INNER JOIN
    dbo.FAC_TIPO_CIRCUITO ON 
    dbo.FAC_CIRCUITO.TPC_ID = dbo.FAC_TIPO_CIRCUITO.TPC_ID ON
     dbo.FAC_FACILIDADES.CTO_ID = dbo.FAC_CIRCUITO.CTO_ID
