//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SislabServiceTeste.SislabService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SislabService.UsuariosSoap")]
    public interface UsuariosSoap {
        
        // CODEGEN: Generating message contract since element name ObtemUsuarioTesteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemUsuarioTeste", ReplyAction="*")]
        SislabServiceTeste.SislabService.ObtemUsuarioTesteResponse ObtemUsuarioTeste(SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemUsuarioTeste", ReplyAction="*")]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemUsuarioTesteResponse> ObtemUsuarioTesteAsync(SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemUsuario", ReplyAction="*")]
        SislabServiceTeste.SislabService.ObtemUsuarioResponse ObtemUsuario(SislabServiceTeste.SislabService.ObtemUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemUsuarioResponse> ObtemUsuarioAsync(SislabServiceTeste.SislabService.ObtemUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemTodosOsDadosUsuario", ReplyAction="*")]
        SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponse ObtemTodosOsDadosUsuario(SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemTodosOsDadosUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponse> ObtemTodosOsDadosUsuarioAsync(SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name remetente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEmail", ReplyAction="*")]
        SislabServiceTeste.SislabService.EnviaEmailResponse EnviaEmail(SislabServiceTeste.SislabService.EnviaEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.EnviaEmailResponse> EnviaEmailAsync(SislabServiceTeste.SislabService.EnviaEmailRequest request);
        
        // CODEGEN: Generating message contract since element name smtpServer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEmailGenerico", ReplyAction="*")]
        SislabServiceTeste.SislabService.EnviaEmailGenericoResponse EnviaEmailGenerico(SislabServiceTeste.SislabService.EnviaEmailGenericoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaEmailGenerico", ReplyAction="*")]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.EnviaEmailGenericoResponse> EnviaEmailGenericoAsync(SislabServiceTeste.SislabService.EnviaEmailGenericoRequest request);
        
        // CODEGEN: Generating message contract since element name numeroAS from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadArquivo", ReplyAction="*")]
        SislabServiceTeste.SislabService.UploadArquivoResponse UploadArquivo(SislabServiceTeste.SislabService.UploadArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.UploadArquivoResponse> UploadArquivoAsync(SislabServiceTeste.SislabService.UploadArquivoRequest request);
        
        // CODEGEN: Generating message contract since element name nomeDoArquivo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadArquivo", ReplyAction="*")]
        SislabServiceTeste.SislabService.DownloadArquivoResponse DownloadArquivo(SislabServiceTeste.SislabService.DownloadArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.DownloadArquivoResponse> DownloadArquivoAsync(SislabServiceTeste.SislabService.DownloadArquivoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemUsuarioTesteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemUsuarioTeste", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.ObtemUsuarioTesteRequestBody Body;
        
        public ObtemUsuarioTesteRequest() {
        }
        
        public ObtemUsuarioTesteRequest(SislabServiceTeste.SislabService.ObtemUsuarioTesteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtemUsuarioTesteRequestBody {
        
        public ObtemUsuarioTesteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemUsuarioTesteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemUsuarioTesteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.ObtemUsuarioTesteResponseBody Body;
        
        public ObtemUsuarioTesteResponse() {
        }
        
        public ObtemUsuarioTesteResponse(SislabServiceTeste.SislabService.ObtemUsuarioTesteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemUsuarioTesteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtemUsuarioTesteResult;
        
        public ObtemUsuarioTesteResponseBody() {
        }
        
        public ObtemUsuarioTesteResponseBody(string ObtemUsuarioTesteResult) {
            this.ObtemUsuarioTesteResult = ObtemUsuarioTesteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemUsuario", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.ObtemUsuarioRequestBody Body;
        
        public ObtemUsuarioRequest() {
        }
        
        public ObtemUsuarioRequest(SislabServiceTeste.SislabService.ObtemUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        public ObtemUsuarioRequestBody() {
        }
        
        public ObtemUsuarioRequestBody(string login, string dominio) {
            this.login = login;
            this.dominio = dominio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.ObtemUsuarioResponseBody Body;
        
        public ObtemUsuarioResponse() {
        }
        
        public ObtemUsuarioResponse(SislabServiceTeste.SislabService.ObtemUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtemUsuarioResult;
        
        public ObtemUsuarioResponseBody() {
        }
        
        public ObtemUsuarioResponseBody(string ObtemUsuarioResult) {
            this.ObtemUsuarioResult = ObtemUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemTodosOsDadosUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemTodosOsDadosUsuario", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequestBody Body;
        
        public ObtemTodosOsDadosUsuarioRequest() {
        }
        
        public ObtemTodosOsDadosUsuarioRequest(SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemTodosOsDadosUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dominio;
        
        public ObtemTodosOsDadosUsuarioRequestBody() {
        }
        
        public ObtemTodosOsDadosUsuarioRequestBody(string login, string dominio) {
            this.login = login;
            this.dominio = dominio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtemTodosOsDadosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtemTodosOsDadosUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponseBody Body;
        
        public ObtemTodosOsDadosUsuarioResponse() {
        }
        
        public ObtemTodosOsDadosUsuarioResponse(SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtemTodosOsDadosUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtemTodosOsDadosUsuarioResult;
        
        public ObtemTodosOsDadosUsuarioResponseBody() {
        }
        
        public ObtemTodosOsDadosUsuarioResponseBody(string ObtemTodosOsDadosUsuarioResult) {
            this.ObtemTodosOsDadosUsuarioResult = ObtemTodosOsDadosUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmail", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.EnviaEmailRequestBody Body;
        
        public EnviaEmailRequest() {
        }
        
        public EnviaEmailRequest(SislabServiceTeste.SislabService.EnviaEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string remetente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string assunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mensagem;
        
        public EnviaEmailRequestBody() {
        }
        
        public EnviaEmailRequestBody(string remetente, string destinatario, string assunto, string mensagem) {
            this.remetente = remetente;
            this.destinatario = destinatario;
            this.assunto = assunto;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.EnviaEmailResponseBody Body;
        
        public EnviaEmailResponse() {
        }
        
        public EnviaEmailResponse(SislabServiceTeste.SislabService.EnviaEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaEmailResult;
        
        public EnviaEmailResponseBody() {
        }
        
        public EnviaEmailResponseBody(string EnviaEmailResult) {
            this.EnviaEmailResult = EnviaEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailGenericoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmailGenerico", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.EnviaEmailGenericoRequestBody Body;
        
        public EnviaEmailGenericoRequest() {
        }
        
        public EnviaEmailGenericoRequest(SislabServiceTeste.SislabService.EnviaEmailGenericoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailGenericoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smtpServer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string numeroPorta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool habilitarSSL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string remetente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string assunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string mensagem;
        
        public EnviaEmailGenericoRequestBody() {
        }
        
        public EnviaEmailGenericoRequestBody(string smtpServer, string numeroPorta, bool habilitarSSL, string remetente, string senha, string destinatario, string assunto, string mensagem) {
            this.smtpServer = smtpServer;
            this.numeroPorta = numeroPorta;
            this.habilitarSSL = habilitarSSL;
            this.remetente = remetente;
            this.senha = senha;
            this.destinatario = destinatario;
            this.assunto = assunto;
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaEmailGenericoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaEmailGenericoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.EnviaEmailGenericoResponseBody Body;
        
        public EnviaEmailGenericoResponse() {
        }
        
        public EnviaEmailGenericoResponse(SislabServiceTeste.SislabService.EnviaEmailGenericoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaEmailGenericoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaEmailGenericoResult;
        
        public EnviaEmailGenericoResponseBody() {
        }
        
        public EnviaEmailGenericoResponseBody(string EnviaEmailGenericoResult) {
            this.EnviaEmailGenericoResult = EnviaEmailGenericoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadArquivo", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.UploadArquivoRequestBody Body;
        
        public UploadArquivoRequest() {
        }
        
        public UploadArquivoRequest(SislabServiceTeste.SislabService.UploadArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numeroAS;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomeDoArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] arquivoByte;
        
        public UploadArquivoRequestBody() {
        }
        
        public UploadArquivoRequestBody(string numeroAS, string nomeDoArquivo, byte[] arquivoByte) {
            this.numeroAS = numeroAS;
            this.nomeDoArquivo = nomeDoArquivo;
            this.arquivoByte = arquivoByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.UploadArquivoResponseBody Body;
        
        public UploadArquivoResponse() {
        }
        
        public UploadArquivoResponse(SislabServiceTeste.SislabService.UploadArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadArquivoResult;
        
        public UploadArquivoResponseBody() {
        }
        
        public UploadArquivoResponseBody(string UploadArquivoResult) {
            this.UploadArquivoResult = UploadArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadArquivo", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.DownloadArquivoRequestBody Body;
        
        public DownloadArquivoRequest() {
        }
        
        public DownloadArquivoRequest(SislabServiceTeste.SislabService.DownloadArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeDoArquivo;
        
        public DownloadArquivoRequestBody() {
        }
        
        public DownloadArquivoRequestBody(string nomeDoArquivo) {
            this.nomeDoArquivo = nomeDoArquivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public SislabServiceTeste.SislabService.DownloadArquivoResponseBody Body;
        
        public DownloadArquivoResponse() {
        }
        
        public DownloadArquivoResponse(SislabServiceTeste.SislabService.DownloadArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadArquivoResult;
        
        public DownloadArquivoResponseBody() {
        }
        
        public DownloadArquivoResponseBody(byte[] DownloadArquivoResult) {
            this.DownloadArquivoResult = DownloadArquivoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuariosSoapChannel : SislabServiceTeste.SislabService.UsuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuariosSoapClient : System.ServiceModel.ClientBase<SislabServiceTeste.SislabService.UsuariosSoap>, SislabServiceTeste.SislabService.UsuariosSoap {
        
        public UsuariosSoapClient() {
        }
        
        public UsuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SislabServiceTeste.SislabService.ObtemUsuarioTesteResponse SislabServiceTeste.SislabService.UsuariosSoap.ObtemUsuarioTeste(SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest request) {
            return base.Channel.ObtemUsuarioTeste(request);
        }
        
        public string ObtemUsuarioTeste() {
            SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest inValue = new SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest();
            inValue.Body = new SislabServiceTeste.SislabService.ObtemUsuarioTesteRequestBody();
            SislabServiceTeste.SislabService.ObtemUsuarioTesteResponse retVal = ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).ObtemUsuarioTeste(inValue);
            return retVal.Body.ObtemUsuarioTesteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemUsuarioTesteResponse> SislabServiceTeste.SislabService.UsuariosSoap.ObtemUsuarioTesteAsync(SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest request) {
            return base.Channel.ObtemUsuarioTesteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemUsuarioTesteResponse> ObtemUsuarioTesteAsync() {
            SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest inValue = new SislabServiceTeste.SislabService.ObtemUsuarioTesteRequest();
            inValue.Body = new SislabServiceTeste.SislabService.ObtemUsuarioTesteRequestBody();
            return ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).ObtemUsuarioTesteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SislabServiceTeste.SislabService.ObtemUsuarioResponse SislabServiceTeste.SislabService.UsuariosSoap.ObtemUsuario(SislabServiceTeste.SislabService.ObtemUsuarioRequest request) {
            return base.Channel.ObtemUsuario(request);
        }
        
        public string ObtemUsuario(string login, string dominio) {
            SislabServiceTeste.SislabService.ObtemUsuarioRequest inValue = new SislabServiceTeste.SislabService.ObtemUsuarioRequest();
            inValue.Body = new SislabServiceTeste.SislabService.ObtemUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.dominio = dominio;
            SislabServiceTeste.SislabService.ObtemUsuarioResponse retVal = ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).ObtemUsuario(inValue);
            return retVal.Body.ObtemUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemUsuarioResponse> SislabServiceTeste.SislabService.UsuariosSoap.ObtemUsuarioAsync(SislabServiceTeste.SislabService.ObtemUsuarioRequest request) {
            return base.Channel.ObtemUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemUsuarioResponse> ObtemUsuarioAsync(string login, string dominio) {
            SislabServiceTeste.SislabService.ObtemUsuarioRequest inValue = new SislabServiceTeste.SislabService.ObtemUsuarioRequest();
            inValue.Body = new SislabServiceTeste.SislabService.ObtemUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.dominio = dominio;
            return ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).ObtemUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponse SislabServiceTeste.SislabService.UsuariosSoap.ObtemTodosOsDadosUsuario(SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest request) {
            return base.Channel.ObtemTodosOsDadosUsuario(request);
        }
        
        public string ObtemTodosOsDadosUsuario(string login, string dominio) {
            SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest inValue = new SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest();
            inValue.Body = new SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.dominio = dominio;
            SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponse retVal = ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).ObtemTodosOsDadosUsuario(inValue);
            return retVal.Body.ObtemTodosOsDadosUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponse> SislabServiceTeste.SislabService.UsuariosSoap.ObtemTodosOsDadosUsuarioAsync(SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest request) {
            return base.Channel.ObtemTodosOsDadosUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioResponse> ObtemTodosOsDadosUsuarioAsync(string login, string dominio) {
            SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest inValue = new SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequest();
            inValue.Body = new SislabServiceTeste.SislabService.ObtemTodosOsDadosUsuarioRequestBody();
            inValue.Body.login = login;
            inValue.Body.dominio = dominio;
            return ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).ObtemTodosOsDadosUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SislabServiceTeste.SislabService.EnviaEmailResponse SislabServiceTeste.SislabService.UsuariosSoap.EnviaEmail(SislabServiceTeste.SislabService.EnviaEmailRequest request) {
            return base.Channel.EnviaEmail(request);
        }
        
        public string EnviaEmail(string remetente, string destinatario, string assunto, string mensagem) {
            SislabServiceTeste.SislabService.EnviaEmailRequest inValue = new SislabServiceTeste.SislabService.EnviaEmailRequest();
            inValue.Body = new SislabServiceTeste.SislabService.EnviaEmailRequestBody();
            inValue.Body.remetente = remetente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            SislabServiceTeste.SislabService.EnviaEmailResponse retVal = ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).EnviaEmail(inValue);
            return retVal.Body.EnviaEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.EnviaEmailResponse> SislabServiceTeste.SislabService.UsuariosSoap.EnviaEmailAsync(SislabServiceTeste.SislabService.EnviaEmailRequest request) {
            return base.Channel.EnviaEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SislabServiceTeste.SislabService.EnviaEmailResponse> EnviaEmailAsync(string remetente, string destinatario, string assunto, string mensagem) {
            SislabServiceTeste.SislabService.EnviaEmailRequest inValue = new SislabServiceTeste.SislabService.EnviaEmailRequest();
            inValue.Body = new SislabServiceTeste.SislabService.EnviaEmailRequestBody();
            inValue.Body.remetente = remetente;
            inValue.Body.destinatario = destinatario;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            return ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).EnviaEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SislabServiceTeste.SislabService.EnviaEmailGenericoResponse SislabServiceTeste.SislabService.UsuariosSoap.EnviaEmailGenerico(SislabServiceTeste.SislabService.EnviaEmailGenericoRequest request) {
            return base.Channel.EnviaEmailGenerico(request);
        }
        
        public string EnviaEmailGenerico(string smtpServer, string numeroPorta, bool habilitarSSL, string remetente, string senha, string destinatario, string assunto, string mensagem) {
            SislabServiceTeste.SislabService.EnviaEmailGenericoRequest inValue = new SislabServiceTeste.SislabService.EnviaEmailGenericoRequest();
            inValue.Body = new SislabServiceTeste.SislabService.EnviaEmailGenericoRequestBody();
            inValue.Body.smtpServer = smtpServer;
            inValue.Body.numeroPorta = numeroPorta;
            inValue.Body.habilitarSSL = habilitarSSL;
            inValue.Body.remetente = remetente;
            inValue.Body.senha = senha;
            inValue.Body.destinatario = destinatario;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            SislabServiceTeste.SislabService.EnviaEmailGenericoResponse retVal = ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).EnviaEmailGenerico(inValue);
            return retVal.Body.EnviaEmailGenericoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.EnviaEmailGenericoResponse> SislabServiceTeste.SislabService.UsuariosSoap.EnviaEmailGenericoAsync(SislabServiceTeste.SislabService.EnviaEmailGenericoRequest request) {
            return base.Channel.EnviaEmailGenericoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SislabServiceTeste.SislabService.EnviaEmailGenericoResponse> EnviaEmailGenericoAsync(string smtpServer, string numeroPorta, bool habilitarSSL, string remetente, string senha, string destinatario, string assunto, string mensagem) {
            SislabServiceTeste.SislabService.EnviaEmailGenericoRequest inValue = new SislabServiceTeste.SislabService.EnviaEmailGenericoRequest();
            inValue.Body = new SislabServiceTeste.SislabService.EnviaEmailGenericoRequestBody();
            inValue.Body.smtpServer = smtpServer;
            inValue.Body.numeroPorta = numeroPorta;
            inValue.Body.habilitarSSL = habilitarSSL;
            inValue.Body.remetente = remetente;
            inValue.Body.senha = senha;
            inValue.Body.destinatario = destinatario;
            inValue.Body.assunto = assunto;
            inValue.Body.mensagem = mensagem;
            return ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).EnviaEmailGenericoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SislabServiceTeste.SislabService.UploadArquivoResponse SislabServiceTeste.SislabService.UsuariosSoap.UploadArquivo(SislabServiceTeste.SislabService.UploadArquivoRequest request) {
            return base.Channel.UploadArquivo(request);
        }
        
        public string UploadArquivo(string numeroAS, string nomeDoArquivo, byte[] arquivoByte) {
            SislabServiceTeste.SislabService.UploadArquivoRequest inValue = new SislabServiceTeste.SislabService.UploadArquivoRequest();
            inValue.Body = new SislabServiceTeste.SislabService.UploadArquivoRequestBody();
            inValue.Body.numeroAS = numeroAS;
            inValue.Body.nomeDoArquivo = nomeDoArquivo;
            inValue.Body.arquivoByte = arquivoByte;
            SislabServiceTeste.SislabService.UploadArquivoResponse retVal = ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).UploadArquivo(inValue);
            return retVal.Body.UploadArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.UploadArquivoResponse> SislabServiceTeste.SislabService.UsuariosSoap.UploadArquivoAsync(SislabServiceTeste.SislabService.UploadArquivoRequest request) {
            return base.Channel.UploadArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SislabServiceTeste.SislabService.UploadArquivoResponse> UploadArquivoAsync(string numeroAS, string nomeDoArquivo, byte[] arquivoByte) {
            SislabServiceTeste.SislabService.UploadArquivoRequest inValue = new SislabServiceTeste.SislabService.UploadArquivoRequest();
            inValue.Body = new SislabServiceTeste.SislabService.UploadArquivoRequestBody();
            inValue.Body.numeroAS = numeroAS;
            inValue.Body.nomeDoArquivo = nomeDoArquivo;
            inValue.Body.arquivoByte = arquivoByte;
            return ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).UploadArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SislabServiceTeste.SislabService.DownloadArquivoResponse SislabServiceTeste.SislabService.UsuariosSoap.DownloadArquivo(SislabServiceTeste.SislabService.DownloadArquivoRequest request) {
            return base.Channel.DownloadArquivo(request);
        }
        
        public byte[] DownloadArquivo(string nomeDoArquivo) {
            SislabServiceTeste.SislabService.DownloadArquivoRequest inValue = new SislabServiceTeste.SislabService.DownloadArquivoRequest();
            inValue.Body = new SislabServiceTeste.SislabService.DownloadArquivoRequestBody();
            inValue.Body.nomeDoArquivo = nomeDoArquivo;
            SislabServiceTeste.SislabService.DownloadArquivoResponse retVal = ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).DownloadArquivo(inValue);
            return retVal.Body.DownloadArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SislabServiceTeste.SislabService.DownloadArquivoResponse> SislabServiceTeste.SislabService.UsuariosSoap.DownloadArquivoAsync(SislabServiceTeste.SislabService.DownloadArquivoRequest request) {
            return base.Channel.DownloadArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SislabServiceTeste.SislabService.DownloadArquivoResponse> DownloadArquivoAsync(string nomeDoArquivo) {
            SislabServiceTeste.SislabService.DownloadArquivoRequest inValue = new SislabServiceTeste.SislabService.DownloadArquivoRequest();
            inValue.Body = new SislabServiceTeste.SislabService.DownloadArquivoRequestBody();
            inValue.Body.nomeDoArquivo = nomeDoArquivo;
            return ((SislabServiceTeste.SislabService.UsuariosSoap)(this)).DownloadArquivoAsync(inValue);
        }
    }
}
