CREATE TABLE [dbo].[FERIADO] (
    [FER_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [FER_DESCRICAO] VARCHAR (255) NOT NULL,
    [FER_DATA]      SMALLDATETIME NOT NULL,
    [FER_ANOINICIO] SMALLINT      NULL,
    [FER_ANOFIM]    SMALLINT      NULL,
    PRIMARY KEY CLUSTERED ([FER_ID] ASC) WITH (FILLFACTOR = 90)
);

