CREATE TABLE [dbo].[Historico_datas] (
    [HD_MARCACAO]      SMALLINT       NOT NULL,
    [AG_NUMERO]        SMALLINT       NOT NULL,
    [HD_RESPONSAVEL]   VARCHAR (20)   NULL,
    [HD_DATAINICIO]    SMALLDATETIME  NULL,
    [HD_DATATERMINO]   SMALLDATETIME  NULL,
    [HD_FLAGREMARCADO] BIT            CONSTRAINT [DF_Historico_datas_HD_FLAGREMARCADO] DEFAULT ((0)) NOT NULL,
    [HD_MOTIVO]        VARCHAR (7000) NULL,
    CONSTRAINT [PK__Historico_datas__31EC6D26] PRIMARY KEY CLUSTERED ([HD_MARCACAO] ASC, [AG_NUMERO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Historico__AG_NU__04E4BC85] FOREIGN KEY ([AG_NUMERO]) REFERENCES [dbo].[Agendamento] ([AG_NUMERO]),
    CONSTRAINT [FK__Historico__HD_RE__03F0984C] FOREIGN KEY ([HD_RESPONSAVEL]) REFERENCES [dbo].[UserCRT] ([USERID])
);


GO
ALTER TABLE [dbo].[Historico_datas] NOCHECK CONSTRAINT [FK__Historico__AG_NU__04E4BC85];


GO
ALTER TABLE [dbo].[Historico_datas] NOCHECK CONSTRAINT [FK__Historico__HD_RE__03F0984C];

