CREATE TABLE [dbo].[Historico_Eventos] (
    [HE_ID]          SMALLINT      IDENTITY (1, 1) NOT NULL,
    [HE_RESPONSAVEL] VARCHAR (20)  NULL,
    [ID_SITUACAO]    SMALLINT      NULL,
    [AG_NUMERO]      SMALLINT      NOT NULL,
    [HE_DATAINICIO]  SMALLDATETIME NOT NULL,
    [HE_DATATERMINO] SMALLDATETIME NULL,
    [HE_MOTIVO]      VARCHAR (255) NULL,
    CONSTRAINT [PK__Historico_Evento__1B0907CE] PRIMARY KEY CLUSTERED ([HE_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Historico__AG_NU__787EE5A0] FOREIGN KEY ([AG_NUMERO]) REFERENCES [dbo].[Agendamento] ([AG_NUMERO]),
    CONSTRAINT [FK__Historico__HE_RE__778AC167] FOREIGN KEY ([HE_RESPONSAVEL]) REFERENCES [dbo].[UserCRT] ([USERID]),
    CONSTRAINT [FK__Historico__ID_SI__76969D2E] FOREIGN KEY ([ID_SITUACAO]) REFERENCES [dbo].[Situacoes] ([ID_SITUACAO])
);


GO
ALTER TABLE [dbo].[Historico_Eventos] NOCHECK CONSTRAINT [FK__Historico__AG_NU__787EE5A0];


GO
ALTER TABLE [dbo].[Historico_Eventos] NOCHECK CONSTRAINT [FK__Historico__HE_RE__778AC167];


GO
ALTER TABLE [dbo].[Historico_Eventos] NOCHECK CONSTRAINT [FK__Historico__ID_SI__76969D2E];

