CREATE TABLE [dbo].[HISTORICO_PLATAFORMA_EQUIPAMENTOS] (
    [HPE_ID]            INT      IDENTITY (1, 1) NOT NULL,
    [HPE_DATAALTERACAO] DATETIME NOT NULL,
    [HPE_TIPOMOVIMENTO] CHAR (1) NOT NULL,
    [EQ_ID]             INT      NOT NULL,
    [S_ID]              SMALLINT NOT NULL,
    PRIMARY KEY CLUSTERED ([HPE_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_HISTORICO_PLATAFORMA_EQUIPAMENTOS_SCE_EQUIPAMENTOS] FOREIGN KEY ([EQ_ID]) REFERENCES [dbo].[SCE_Equipamentos] ([EQ_ID]),
    CONSTRAINT [FK_HISTORICO_PLATAFORMA_EQUIPAMENTOS_SERVICOS_PLATAFORMAS] FOREIGN KEY ([S_ID]) REFERENCES [dbo].[Servicos_Plataformas] ([S_ID])
);


GO
ALTER TABLE [dbo].[HISTORICO_PLATAFORMA_EQUIPAMENTOS] NOCHECK CONSTRAINT [FK_HISTORICO_PLATAFORMA_EQUIPAMENTOS_SCE_EQUIPAMENTOS];


GO
ALTER TABLE [dbo].[HISTORICO_PLATAFORMA_EQUIPAMENTOS] NOCHECK CONSTRAINT [FK_HISTORICO_PLATAFORMA_EQUIPAMENTOS_SERVICOS_PLATAFORMAS];

