CREATE TABLE [dbo].[LB_TIPOACAOTOMADA] (
    [TAT_ID]        INT       NOT NULL,
    [TAT_DESCRICAO] CHAR (50) NOT NULL,
    CONSTRAINT [PK_LB_TIPOACAOTOMADA] PRIMARY KEY CLUSTERED ([TAT_ID] ASC) WITH (FILLFACTOR = 90)
);

