CREATE TABLE [dbo].[LB_TipoOcorrencia] (
    [LBTO_ID]        SMALLINT       IDENTITY (1, 1) NOT NULL,
    [LBTO_DESCRICAO] NVARCHAR (400) NULL,
    CONSTRAINT [PK__LB_TipoOcorrenci__15502E78] PRIMARY KEY CLUSTERED ([LBTO_ID] ASC) WITH (FILLFACTOR = 90)
);

