CREATE TABLE [dbo].[LogBook_Agendamento] (
    [LB_ID]     SMALLINT NOT NULL,
    [AG_NUMERO] SMALLINT NOT NULL,
    PRIMARY KEY CLUSTERED ([LB_ID] ASC, [AG_NUMERO] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__LogBook_A__AG_NU__74AE54BC] FOREIGN KEY ([AG_NUMERO]) REFERENCES [dbo].[Agendamento] ([AG_NUMERO]),
    CONSTRAINT [FK__LogBook_A__LB_ID__75A278F5] FOREIGN KEY ([LB_ID]) REFERENCES [dbo].[LB_LogBook] ([LB_ID])
);


GO
ALTER TABLE [dbo].[LogBook_Agendamento] NOCHECK CONSTRAINT [FK__LogBook_A__AG_NU__74AE54BC];


GO
ALTER TABLE [dbo].[LogBook_Agendamento] NOCHECK CONSTRAINT [FK__LogBook_A__LB_ID__75A278F5];

