CREATE TABLE [dbo].[Orgao] (
    [ORGA_ID]          SMALLINT      IDENTITY (1, 1) NOT NULL,
    [ORGA_SIGLA]       VARCHAR (20)  NOT NULL,
    [ORGA_DESCRICAO]   VARCHAR (100) NOT NULL,
    [ORGA_FAX]         VARCHAR (50)  NULL,
    [ORGA_RAMAL]       VARCHAR (50)  NULL,
    [ORGA_EXIBIR]      BIT           CONSTRAINT [DF_Orgao_ORGA_EXIBIR] DEFAULT ((0)) NOT NULL,
    [ORGA_TIPO]        BIT           NOT NULL,
    [ORGA_USERIDCHEFE] NVARCHAR (20) NOT NULL,
    [ORGA_HIERARQUIA]  SMALLINT      NULL,
    CONSTRAINT [PK__Orgao__0BC6C43E] PRIMARY KEY CLUSTERED ([ORGA_ID] ASC) WITH (FILLFACTOR = 90)
);

