CREATE TABLE [dbo].[PesquisaSatisfacao] (
    [PSQ_Id]               INT            IDENTITY (1, 1) NOT NULL,
    [PSQ_UsernameCadastro] NVARCHAR (50)  NULL,
    [PSQ_IPCadastro]       NVARCHAR (50)  NULL,
    [PSQ_DataHoraCadastro] DATETIME       NULL,
    [PSQ_NAg]              INT            NULL,
    [PSQ_Nome]             NVARCHAR (150) NULL,
    [PSQ_Telefone]         NVARCHAR (50)  NULL,
    [PSQ_Email]            NVARCHAR (50)  NULL,
    [PSQ_OrgaoEmpresa]     NVARCHAR (50)  NULL,
    [PSQ_Origem]           NVARCHAR (50)  NULL,
    [PSQ_R1]               FLOAT (53)     NULL,
    [PSQ_R2]               FLOAT (53)     NULL,
    [PSQ_R3]               FLOAT (53)     NULL,
    [PSQ_R4]               FLOAT (53)     NULL,
    [PSQ_R5]               FLOAT (53)     NULL,
    [PSQ_R6]               FLOAT (53)     NULL,
    [PSQ_R7]               FLOAT (53)     NULL,
    [PSQ_R8]               FLOAT (53)     NULL,
    [PSQ_R9]               FLOAT (53)     NULL,
    [PSQ_R10]              FLOAT (53)     NULL,
    [PSQ_R11]              FLOAT (53)     NULL,
    [PSQ_C1]               NTEXT          NULL,
    [PSQ_C2]               NTEXT          NULL,
    [PSQ_C3]               NTEXT          NULL,
    [PSQ_C4]               NTEXT          NULL,
    [PSQ_C5]               NTEXT          NULL,
    [PSQ_C6]               NTEXT          NULL,
    [PSQ_C7]               NTEXT          NULL,
    [PSQ_C8]               NTEXT          NULL,
    [PSQ_C9]               NTEXT          NULL,
    [PSQ_C10]              NTEXT          NULL,
    [PSQ_C11]              NTEXT          NULL,
    [PSQ_C_3]              NTEXT          NULL,
    [PSQ_C_4]              NTEXT          NULL
);

