CREATE TABLE [dbo].[Servicos_Plataformas] (
    [S_ID]        SMALLINT      IDENTITY (1, 1) NOT NULL,
    [S_TIPO]      VARCHAR (200) NULL,
    [S_DESCRICAO] VARCHAR (200) NULL,
    [S_SERVICO]   BIT           NOT NULL,
    [S_ID_PAI]    SMALLINT      NULL,
    CONSTRAINT [PK__Servicos_Platafo__35BCFE0A] PRIMARY KEY CLUSTERED ([S_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SERVICOS_PLATAFORMAS_SERVICOS_PLATAFORMAS_PAI] FOREIGN KEY ([S_ID_PAI]) REFERENCES [dbo].[Servicos_Plataformas] ([S_ID])
);


GO
ALTER TABLE [dbo].[Servicos_Plataformas] NOCHECK CONSTRAINT [FK_SERVICOS_PLATAFORMAS_SERVICOS_PLATAFORMAS_PAI];

