CREATE TABLE [dbo].[Situacoes] (
    [ID_SITUACAO] SMALLINT       IDENTITY (1, 1) NOT NULL,
    [S_DESCRICAO] VARCHAR (200)  NULL,
    [S_OS]        BIT            NOT NULL,
    [S_MENSAGEM]  VARCHAR (8000) NULL,
    CONSTRAINT [PK__Situacoes__07F6335A] PRIMARY KEY CLUSTERED ([ID_SITUACAO] ASC) WITH (FILLFACTOR = 90)
);

