CREATE TABLE [dbo].[Situacoes_Situacoes] (
    [SITUACAO_ATUAL]   SMALLINT NOT NULL,
    [SITUACAO_PROXIMA] SMALLINT NOT NULL,
    PRIMARY KEY CLUSTERED ([SITUACAO_ATUAL] ASC, [SITUACAO_PROXIMA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Situacoes__SITUA__6E01572D] FOREIGN KEY ([SITUACAO_PROXIMA]) REFERENCES [dbo].[Situacoes] ([ID_SITUACAO]),
    CONSTRAINT [FK__Situacoes__SITUA__6EF57B66] FOREIGN KEY ([SITUACAO_ATUAL]) REFERENCES [dbo].[Situacoes] ([ID_SITUACAO])
);


GO
ALTER TABLE [dbo].[Situacoes_Situacoes] NOCHECK CONSTRAINT [FK__Situacoes__SITUA__6E01572D];


GO
ALTER TABLE [dbo].[Situacoes_Situacoes] NOCHECK CONSTRAINT [FK__Situacoes__SITUA__6EF57B66];

