CREATE TABLE [dbo].[TAREFAS] (
    [TAR_ID]        SMALLINT      IDENTITY (1, 1) NOT NULL,
    [TAR_DESCRICAO] VARCHAR (255) NOT NULL,
    CONSTRAINT [PK__TAREFAS__4F52B2DB] PRIMARY KEY CLUSTERED ([TAR_ID] ASC) WITH (FILLFACTOR = 90)
);

