/* parece que essa procedure não está no banco de dados! Preciso verificar na produção!!! */

USE [SISLAB]
GO

/****** Object:  StoredProcedure [dbo].[sp_CadLogBookAcaoTomada]    Script Date: 13/07/2021 16:17:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--drop PROCEDURE [dbo].[sp_CadLogBookAcaoTomada]

CREATE PROCEDURE [dbo].[sp_CadLogBookAcaoTomada]
	@pACT_ID INT = NULL OUTPUT,
	@pACT_LB INT,
	@pACT_DESCRICAO VARCHAR(255),
	@pACT_RESPONSAVEL VARCHAR(20),
	@pACT_EXECUTANTE VARCHAR(200),
	@pACT_PRAZO SMALLDATETIME,
	@pACT_DATACONCLUSAO SMALLDATETIME,
	@pACT_EFICACIA TINYINT,
	@pACT_OBS TEXT,
	@pACT_TIPOACAO INT,
	@pACT_ARQUIVO VARCHAR(5000),
	@pACT_USUARIOCADASTROU VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRANSACTION

	IF @pACT_ID IS NULL OR 	@pACT_ID = 0 BEGIN
		INSERT INTO LB_ACOESTOMADAS 
					(ACT_LB, ACT_DESCRICAO, ACT_EXECUTANTE, ACT_PRAZO, 
					ACT_DATACONCLUSAO, ACT_EFICACIA, ACT_OBS, ACT_TIPOACAO, ACT_RESPONSAVEL)
			VALUES (@pACT_LB, @pACT_DESCRICAO, @pACT_EXECUTANTE, @pACT_PRAZO,
					@pACT_DATACONCLUSAO, @pACT_EFICACIA, @pACT_OBS, @pACT_TIPOACAO, @pACT_RESPONSAVEL)
		IF @@ERROR <> 0 BEGIN
			ROLLBACK TRANSACTION
			RAISERROR( 'Não foi possível incluir esta ação.', 16, 1 )
			SELECT -1 AS SAIDA
			RETURN -1
		END
		SET @pACT_ID = @@IDENTITY
	END
	ELSE BEGIN
		UPDATE LB_ACOESTOMADAS 
			SET ACT_LB = @pACT_LB,
			ACT_DESCRICAO = @pACT_DESCRICAO,
			ACT_RESPONSAVEL = @pACT_RESPONSAVEL,
			ACT_EXECUTANTE = @pACT_EXECUTANTE,
			ACT_PRAZO = @pACT_PRAZO,
			ACT_DATACONCLUSAO = @pACT_DATACONCLUSAO, 
			ACT_EFICACIA = @pACT_EFICACIA, 
			ACT_OBS = @pACT_OBS, 
			ACT_TIPOACAO = @pACT_TIPOACAO
			WHERE ACT_ID = @pACT_ID
		IF @@ERROR <> 0 BEGIN
			ROLLBACK TRANSACTION
			RAISERROR( 'Não foi possível atualizar esta ação.', 16, 1 )
			SELECT -1 AS SAIDA
			RETURN -1
		END
	END


	IF @pACT_ARQUIVO IS NOT NULL
	BEGIN
		INSERT INTO LB_ACOESTOMADAS_ARQUIVOS (ACT_ID, LB_ID, ACA_LINK, ACA_USUARIOCADASTROU, ACA_DATACADASTRO)
			VALUES (@pACT_ID, @pACT_LB, @pACT_ARQUIVO, @pACT_USUARIOCADASTROU, GETDATE())
		IF @@ERROR <> 0 BEGIN
			ROLLBACK TRANSACTION
			RAISERROR( 'Não foi possível anexar o arquivo desta esta ação.', 16, 1 )
			SELECT -1 AS SAIDA
			RETURN -1
		END
	END

	COMMIT TRANSACTION
	SELECT @pACT_ID AS SAIDA
	RETURN @pACT_ID
END
GO
