CREATE  VIEW [dbo].[vw_SCE_Reserva_Equipamentos]
AS
SELECT A.AG_NUMERO, 
	CONVERT(DATETIME, A.AG_DATAINICIO, 103) as AG_DATAINICIO,
	CONVERT(DATETIME, A.AG_DATATERMINO, 103) AS AG_DATATERMINO,
	CONVERT(DATETIME, R.RES_DATACADASTRO, 103) AS RES_DATACADASTRO,
	R.RES_RESPONSAVEL, Amb.AMB_ID, Amb.AMB_NOME, 
	E.EQ_ID, E.EQ_CODIGOBARRAS, E.EQ_NUMEROSERIE, E.EQ_LOCALIZACAO, 
	E.STATUS,
	CASE
		WHEN STATUS = 0 THEN 'Cadastrado'
		WHEN STATUS = 2 THEN 'Em Uso'
		WHEN STATUS = 1 THEN 'Estoque'
		WHEN STATUS = 3 THEN 'Expedido'
	END AS DESC_STATUS,
	E.EQ_INSTRUMENTAL, E.EQ_PROPRIEDADE, E.EQ_CONFORME, R.RES_OBSERVACAO,
	CONVERT(DATETIME, RE.REQ_DATAINICIO, 103) AS REQ_DATAINICIO,
	CONVERT(DATETIME, RE.REQ_DATATERMINO, 103) AS REQ_DATATERMINO,
	RE.REQ_ACEITO, RE.REQ_MOVIMENTOU, M.MOD_ID, M.MOD_CODNOME, M.mod_descricao, 
	F.fab_id, F.fab_nome, U.NOME AS NOME_RESPONSAVEL
FROM
	SCE_Reserva R 
	INNER JOIN UserCRT U ON R.RES_RESPONSAVEL = U.USERID
	INNER JOIN SCE_Reserva_Equipamentos RE ON RE.AG_NUMERO = R.AG_NUMERO
	INNER JOIN Agendamento A ON RE.AG_NUMERO = A.AG_NUMERO
	INNER JOIN SCE_Equipamentos E ON RE.EQ_ID = E.EQ_ID
	INNER JOIN SCE_Modelos M ON E.MOD_ID = M.MOD_ID
	INNER JOIN SCE_Fabricantes F ON M.FAB_ID = F.fab_id
	LEFT JOIN Ambientes Amb ON Amb.AMB_ID = RE.AMB_ID

