CREATE PROCEDURE [dbo].[SP_AG_BUSCA_FERIADOS]

@data	VARCHAR(10)

 AS

DECLARE @datainicio DATETIME, @datafim DATETIME
SET @datainicio = CONVERT(DATETIME, @data, 103)
SET @datafim =DATEADD(DD, 13, CONVERT(DATETIME, @data, 103))

SELECT FER_ID, FER_ANOINICIO, FER_ANOFIM, FER_DATA,
	CONVERT(DATETIME, CAST(DAY(FER_DATA) AS VARCHAR)+'/'+CAST(MONTH(FER_DATA) AS VARCHAR)+'/'+CAST(YEAR(@datainicio) AS VARCHAR), 103) AS DATA_FERIADO,
	FER_DESCRICAO 
FROM FERIADO
WHERE(   
		( FER_ANOINICIO <= YEAR(CONVERT(DATETIME, @data, 103)) AND FER_ANOFIM >= YEAR(CONVERT(DATETIME, @data, 103)) ) 
OR		( FER_ANOINICIO IS NULL AND FER_ANOFIM IS NULL )    
	)
AND	(
	( @datainicio <= CONVERT(DATETIME, CAST(DAY(FER_DATA) AS VARCHAR)+'/'+CAST(MONTH(FER_DATA) AS VARCHAR)+'/'+CAST(YEAR(@datainicio) AS VARCHAR), 103)
AND	@datafim >= CONVERT(DATETIME, CAST(DAY(FER_DATA) AS VARCHAR)+'/'+CAST(MONTH(FER_DATA) AS VARCHAR)+'/'+CAST(YEAR(@datainicio) AS VARCHAR), 103) )
OR
	( @datainicio <= CONVERT(DATETIME, CAST(DAY(FER_DATA) AS VARCHAR)+'/'+CAST(MONTH(FER_DATA) AS VARCHAR)+'/'+CAST(YEAR(@datafim) AS VARCHAR), 103)
AND	@datafim >= CONVERT(DATETIME, CAST(DAY(FER_DATA) AS VARCHAR)+'/'+CAST(MONTH(FER_DATA) AS VARCHAR)+'/'+CAST(YEAR(@datafim) AS VARCHAR), 103) )
	)
ORDER BY DATA_FERIADO

PRINT CAST(@datainicio AS VARCHAR) + '  a  '+ CAST(@datafim AS VARCHAR)
