CREATE PROCEDURE [dbo].[SP_AG_CADASTRA_TAREFA]

@tar_descricao		VARCHAR(255)

AS

SET NOCOUNT ON

SELECT TAR_ID FROM TAREFAS WHERE TAR_DESCRICAO = @tar_descricao

IF @@ROWCOUNT = 0 
BEGIN
	INSERT INTO TAREFAS (TAR_DESCRICAO)
	VALUES (@tar_descricao)
	IF @@ERROR > 0
		RETURN -1
	ELSE
		RETURN @@IDENTITY
END
ELSE
	RETURN -2  -- Nome já cadastrado



