CREATE PROCEDURE [dbo].[SP_FAC_ATUALIZA_LOCAL_ESPECIFICO]
@leeID		INTEGER,
@leeNome	VARCHAR(50),
@lgeID		INTEGER

AS

SET NOCOUNT ON

UPDATE FAC_LOCAIS_ESPECIFICOS_EQUIP SET LGE_ID = @lgeID, LEE_NOME = UPPER( @leeNome) WHERE LEE_ID = @leeID

IF @@ERROR > 0
	RETURN -1
ELSE
	RETURN 1

