CREATE PROCEDURE [dbo].[SP_FAC_ATUALIZA_FAMILIA_TIPO_COMPONENTE]
@ftcID		INTEGER,
@ftcNome	VARCHAR(200)

AS

SET NOCOUNT ON

UPDATE FAC_FAMILIA_TIPO_COMPONENTE SET FTC_NOME = UPPER( @ftcNome ) WHERE FTC_ID = @ftcID

IF @@ERROR > 0
	RETURN -1--erro na inserção
ELSE
	RETURN 1

