CREATE PROCEDURE [dbo].[SP_FAC_ATUALIZA_CARACTERISTICA]
@carID		INTEGER,
@carNome	VARCHAR(50),
@carDefinicao	VARCHAR(5000)

AS

SET NOCOUNT ON

UPDATE FAC_CARACTERISTICAS SET CAR_NOME = UPPER( @carNome ), CAR_DEFINICAO = UPPER( @carDefinicao ) WHERE CAR_ID = @carID

IF @@ERROR > 0
	RETURN -1
ELSE
	RETURN 1

