CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_TIPO_COMPONENTE]
@tpcNome	VARCHAR(50),
@ftcID		INTEGER,
@fabID		INTEGER

AS

SET NOCOUNT ON

DECLARE @tmp INTEGER

SELECT @tmp = TPC_ID FROM FAC_TIPO_COMPONENTE WHERE UPPER( @tpcNome ) = TPC_NOME AND FTC_ID = @ftcID AND FAB_ID = @fabID

IF @@ROWCOUNT > 0
	RETURN @tmp
ELSE BEGIN

	INSERT INTO FAC_TIPO_COMPONENTE (TPC_NOME, FTC_ID, FAB_ID) VALUES ( UPPER( @tpcNome ), @ftcID, @fabID )

	IF @@ERROR > 0
		RETURN -1
	ELSE
		RETURN @@IDENTITY
END

