CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_LOCAL_ESPECIFICO]
@lgeID		INTEGER,
@leeNome	VARCHAR(50)

AS

SET NOCOUNT ON

DECLARE @tmp INTEGER

SELECT @tmp = LEE_ID FROM FAC_LOCAIS_ESPECIFICOS_EQUIP WHERE LGE_ID = @lgeID AND LEE_NOME = UPPER(@leeNome)

IF @@ROWCOUNT > 0
	RETURN @tmp
ELSE BEGIN
	INSERT INTO FAC_LOCAIS_ESPECIFICOS_EQUIP (LGE_ID, LEE_NOME) VALUES ( @lgeID, UPPER(@leeNome) )

	IF @@ERROR > 0
		RETURN -1
	ELSE
		RETURN @@IDENTITY
END

