CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_FABRICANTE]
@fabNome	VARCHAR(200)

AS

SET NOCOUNT ON

DECLARE @tmp INTEGER

SELECT @tmp = FAB_ID FROM FAC_FABRICANTE_TIPO_COMPONENTE WHERE FAB_NOME = UPPER( @fabNome )

IF @@ROWCOUNT > 0
	RETURN @tmp

INSERT INTO FAC_FABRICANTE_TIPO_COMPONENTE (FAB_NOME) VALUES ( UPPER ( @fabNome ) )

IF @@ERROR > 0
	RETURN -1 --erro ao inserir
ELSE
	RETURN @@IDENTITY


