CREATE PROCEDURE [dbo].[SP_FAC_ATUALIZA_LOCAL_GENERICO]
@lgeID		INTEGER,
@lgeNome	VARCHAR(50),
@lgeTipo	CHAR

AS

SET NOCOUNT ON

UPDATE FAC_LOCAIS_GENERICOS_EQUIP SET LGE_NOME = UPPER( @lgeNome), LGE_TIPO = @lgeTipo WHERE LGE_ID = @lgeID

IF @@ERROR > 0
	RETURN -1
ELSE
	RETURN 1

