CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_LOCAL_GENERICO]
@lgeNome	VARCHAR(50),
@lgeTipo	CHAR

AS

SET NOCOUNT ON

DECLARE @tmp INTEGER

SELECT @tmp = LGE_ID FROM FAC_LOCAIS_GENERICOS_EQUIP WHERE UPPER(@lgeNome) = LGE_NOME AND UPPER(@lgeTipo) = LGE_TIPO

IF @@ROWCOUNT > 0
	RETURN @tmp
ELSE BEGIN
	INSERT INTO FAC_LOCAIS_GENERICOS_EQUIP (LGE_NOME, LGE_TIPO) VALUES ( UPPER(@lgeNome), UPPER(@lgeTipo) )

	IF @@ERROR > 0
		RETURN -1 --erro na inserção
	ELSE
		RETURN @@IDENTITY
END

