CREATE PROCEDURE [dbo].[SP_FAC_EXCLUI_LOCAL_ESPECIFICO]
@leeID	INTEGER

AS

SET NOCOUNT ON

DELETE FROM FAC_LOCAIS_ESPECIFICOS_EQUIP WHERE LEE_ID = @leeID
IF @@ERROR > 0
	RETURN - 1 --erro na exclusão
ELSE
	RETURN 1

