CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_FAMILIA_TIPO_COMPONENTE]
@ftcNome	VARCHAR(200)

AS

SET NOCOUNT ON

DECLARE @tmp INTEGER

SELECT @tmp = FTC_ID FROM FAC_FAMILIA_TIPO_COMPONENTE WHERE FTC_NOME = UPPER( @ftcNome )

IF @@ROWCOUNT > 0
	RETURN @tmp

INSERT INTO FAC_FAMILIA_TIPO_COMPONENTE ( FTC_NOME ) VALUES ( UPPER( @ftcNome ) )

IF @@ERROR > 0
	RETURN -1--erro na inserção
ELSE
	RETURN @@IDENTITY

