CREATE PROCEDURE [dbo].[SP_FAC_CADASTRA_FACILIDADE]
@ctoID		INTEGER,
@cptID		INTEGER,
@intID		INTEGER,
@facOrdem	TINYINT

AS

SET NOCOUNT ON

IF @facOrdem IS NULL

	SELECT @facOrdem =
				CASE
					WHEN MAX(FAC_ORDEM) IS NULL THEN 0
					ELSE MAX(FAC_ORDEM) + 1
				END
	FROM FAC_FACILIDADES WHERE CPT_ID = @cptID AND CTO_ID = @ctoID
	
BEGIN TRAN

	SELECT FAC_ID FROM FAC_FACILIDADES WHERE FAC_ORDEM = @facOrdem AND CTO_ID = @ctoID

	IF @@ROWCOUNT > 0 BEGIN

		UPDATE FAC_FACILIDADES SET FAC_ORDEM = FAC_ORDEM + 1 WHERE FAC_ORDEM >= @facOrdem AND CTO_ID = @ctoID

		IF @@ERROR > 0 BEGIN
			ROLLBACK TRAN
			RETURN -1 --erro de atualização
		END
	END

	INSERT INTO FAC_FACILIDADES (CPT_ID, CTO_ID, FAC_ORDEM,Tipo_Interface_Id) VALUES (@cptID, @ctoID, @facOrdem,@intID)

	IF @@ERROR > 0 BEGIN
		ROLLBACK TRAN
		RETURN -2 --erro na inserção
	END
	ELSE BEGIN
		COMMIT TRAN
		RETURN @@IDENTITY
	END


