CREATE PROCEDURE [dbo].[SP_FAC_EXCLUI_FACILIDADE]
@facID	INTEGER

AS

SET NOCOUNT ON

DECLARE @tmp1 TINYINT, @tmp2 INTEGER

SELECT @tmp1 = FAC_ORDEM, @tmp2 = CTO_ID FROM FAC_FACILIDADES WHERE FAC_ID = @facID

IF @@ROWCOUNT = 0
	RETURN -1 --erro: FAC_ID não existia
ELSE BEGIN

	BEGIN TRAN

		DELETE FROM FAC_FACILIDADES WHERE FAC_ID = @facID
		IF @@ERROR > 0 BEGIN
			ROLLBACK TRAN
			RETURN - 2 --erro na exclusão
		END
		ELSE BEGIN
			IF @@ROWCOUNT > 0 BEGIN
				UPDATE FAC_FACILIDADES SET FAC_ORDEM = FAC_ORDEM - 1 WHERE FAC_ORDEM > @tmp1 AND CTO_ID = @tmp2
				IF @@ERROR > 0 BEGIN
					ROLLBACK TRAN
					RETURN -3 --erro na atualização
				END
			END
			ELSE BEGIN
				COMMIT TRAN
				RETURN 1 --OK
			END
		END
END

