
CREATE PROCEDURE [dbo].[sp_LogEvento]
	@USER_ID VARCHAR(20)
	,@MODULO VARCHAR(10)
	,@MSG VARCHAR(8000)
AS
BEGIN
	DECLARE @msg_erro VARCHAR(8000), @user_nome VARCHAR(100)

	SET NOCOUNT ON

	--LOG
	INSERT INTO SCE_Historico(ID_USUARIO, ACAO, DATA, MODULO)
		VALUES (@USER_ID, @MSG, CONVERT(VARCHAR, GETDATE(), 120), @MODULO)
	IF @@ERROR <> 0 BEGIN
		ROLLBACK TRANSACTION
		RAISERROR( 'Não foi possível inserir no histórico', 16, 1)
		RETURN -1
	END

	RETURN 0
END
