/****
	Alterações para permitir que o nome do usuário do sistema seja o email ao invés de ser apenas o LOGIN

	EMBRATEL
	CRT
	Sislab
****/

ALTER TABLE HISTORICO_ARQUIVOS DROP CONSTRAINT FK_Historico_Arquivos_UserCRT
go
ALTER TABLE HISTORICO_ARQUIVOS ALTER COLUMN HA_USUARIO varchar(70) not null
go

ALTER TABLE Historico_datas DROP CONSTRAINT FK__Historico__HD_RE__03F0984C
go
ALTER TABLE Historico_datas ALTER COLUMN HD_RESPONSAVEL varchar(70)  null
go

ALTER TABLE Historico_Eventos DROP CONSTRAINT FK__Historico__HE_RE__778AC167
go
ALTER TABLE Historico_Eventos ALTER COLUMN HE_RESPONSAVEL varchar(70)  null
go

ALTER TABLE Historico_EventosOS DROP CONSTRAINT FK__Historico__HEOS___2180FB33
go
ALTER TABLE Historico_EventosOS ALTER COLUMN HEOS_RESPONSAVEL varchar(70)  null
go

ALTER TABLE LB_ACOESTOMADAS DROP CONSTRAINT FK_LB_ACOESTOMADAS_USERCRT
go
ALTER TABLE LB_ACOESTOMADAS ALTER COLUMN ACT_RESPONSAVEL varchar(70)  null
go

ALTER TABLE LB_LogBook DROP CONSTRAINT FK_LB_LogBook_UserCRT
go
ALTER TABLE LB_LogBook ALTER COLUMN LB_RATRESPONSAVEL varchar(70) null
go
ALTER TABLE LB_LogBook ALTER COLUMN LB_USERNAMECAD varchar(70) null
go

ALTER TABLE Ordem_de_Servico DROP CONSTRAINT FK_Ordem_de_Servico_UserCRT
go
ALTER TABLE Ordem_de_Servico ALTER COLUMN OS_RESPONSAVEL varchar(70)  null
go

ALTER TABLE Plantao DROP CONSTRAINT FK__Plantao__PLA_USE__0F624AF8
go
ALTER TABLE Plantao ALTER COLUMN PLA_USERID varchar(70)  null
go

ALTER TABLE SCE_Reserva DROP CONSTRAINT FK_SCE_Reserva_UserCRT
go
ALTER TABLE SCE_Reserva ALTER COLUMN RES_RESPONSAVEL varchar(70) not null
go

ALTER TABLE TAREFAS_PREVISTAS DROP CONSTRAINT FK_TAREFAS_PREVISTAS_UserCRT
go
ALTER TABLE TAREFAS_PREVISTAS ALTER COLUMN PES_USERNAME varchar(70)  null
go

ALTER TABLE agendamento alter column AG_RAT varchar(70) null
go
ALTER TABLE agendamento alter column AG_RESPONSAVEL varchar(70) null
go

ALTER TABLE UserCRT DROP CONSTRAINT PK__UserCRT__0DAF0CB0
go
ALTER TABLE UserCRT alter column userid varchar(70) not null
go

----------------------------------

ALTER TABLE UserCRT ADD CONSTRAINT PK_UserCRT PRIMARY KEY (USERID)
go
ALTER TABLE HISTORICO_ARQUIVOS 
	ADD CONSTRAINT FK_Historico_Arquivos_UserCRT FOREIGN KEY (HA_USUARIO)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE Historico_datas 
	ADD CONSTRAINT FK_Historico_datas_UserCRT FOREIGN KEY (HD_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE Historico_Eventos 
	ADD CONSTRAINT FK_Historico_Eventos_UserCRT FOREIGN KEY (HE_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE Historico_EventosOS
	ADD CONSTRAINT FK_Historico_EventosOS_UserCRT FOREIGN KEY (HEOS_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE LB_ACOESTOMADAS
	ADD CONSTRAINT FK_LB_ACOESTOMADAS_USERCRT FOREIGN KEY (ACT_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE LB_LogBook
	ADD CONSTRAINT FK_LB_LogBook_RAT_UserCRT FOREIGN KEY (LB_RATRESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE Ordem_de_Servico
	ADD CONSTRAINT FK_Ordem_de_Servico_UserCRT FOREIGN KEY (OS_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE Plantao
	ADD CONSTRAINT FK_Plantao_UserCRT FOREIGN KEY (PLA_USERID)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE SCE_Reserva
	ADD CONSTRAINT FK_SCE_Reserva_UserCRT FOREIGN KEY (RES_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE TAREFAS_PREVISTAS
	ADD CONSTRAINT FK_TAREFAS_PREVISTAS_UserCRT FOREIGN KEY (PES_USERNAME)
		REFERENCES UserCRT (UserID)
GO
ALTER TABLE agendamento ADD CONSTRAINT FK_Agendamento_UserCRT_RAT foreign key (AG_RAT) references UserCRT (Userid)
go


ALTER TABLE Agendamento ADD AG_MATRICULARESP varchar(50)
go
ALTER TABLE Agendamento ADD AG_NOMERESP varchar(300)
go
ALTER TABLE Agendamento ADD AG_TELEFONERESP varchar(50)
go
