/****

	ALTERAÇÕES PARA PERMITIR QUE O NOME DO USUÁRIO DO SISTEMA SEJA O EMAIL AO INVÉS DE SER APENAS O LOGIN

	EMBRATEL
	CRT
	Sislab
****/

-- BEGIN TRANSACTION
-- ROLLBACK TRANSACTION
-- COMMIT TRANSACTION

/*
	ALTERAMOS O TAMANHO DOS CAMPOS E EXCLUÍMOS AS CONSTRAINTS
*/

ALTER TABLE PARTICIPANTES_EXTERNOS ALTER COLUMN PE_USERNAME VARCHAR(80) NULL
GO

ALTER TABLE EquipeEmbratel ALTER COLUMN UserId_Gerente VARCHAR(80) NOT NULL
GO
ALTER TABLE EquipeEmbratel ALTER COLUMN UserId_Membro VARCHAR(80) NOT NULL
GO

ALTER TABLE Plantao DROP CONSTRAINT FK__Plantao__PLA_USE__0F624AF8
GO
ALTER TABLE Plantao ALTER COLUMN PLA_USERID VARCHAR(80) NULL
GO

ALTER TABLE TAREFAS_PREVISTAS DROP CONSTRAINT FK_TAREFAS_PREVISTAS_UserCRT
GO
ALTER TABLE TAREFAS_PREVISTAS ALTER COLUMN PES_USERNAME VARCHAR(80)  null
GO

ALTER TABLE Historico_Eventos DROP CONSTRAINT FK__Historico__HE_RE__778AC167
GO
ALTER TABLE Historico_Eventos ALTER COLUMN HE_RESPONSAVEL VARCHAR(80)  null
GO

ALTER TABLE Historico_EventosOS DROP CONSTRAINT FK__Historico__HEOS___2180FB33
GO
ALTER TABLE Historico_EventosOS ALTER COLUMN HEOS_RESPONSAVEL VARCHAR(80)  null
GO

ALTER TABLE Ordem_de_Servico DROP CONSTRAINT FK_Ordem_de_Servico_UserCRT
go
ALTER TABLE Ordem_de_Servico ALTER COLUMN OS_RESPONSAVEL VARCHAR(80) null
go

ALTER TABLE SCE_Reserva DROP CONSTRAINT FK_SCE_Reserva_UserCRT
go
ALTER TABLE SCE_Reserva ALTER COLUMN RES_RESPONSAVEL VARCHAR(80) NOT NULL
GO

ALTER TABLE ARQUIVOS ALTER COLUMN ARQ_RESPONSAVEL VARCHAR(80)
GO
ALTER TABLE ARQUIVOS ALTER COLUMN USERIDCADASTRO VARCHAR(80)
GO

ALTER TABLE HISTORICO_ARQUIVOS DROP CONSTRAINT FK_Historico_Arquivos_UserCRT
GO
ALTER TABLE HISTORICO_ARQUIVOS ALTER COLUMN HA_USUARIO VARCHAR(80) not null
GO

ALTER TABLE Historico_datas DROP CONSTRAINT FK__Historico__HD_RE__03F0984C
GO
ALTER TABLE Historico_datas ALTER COLUMN HD_RESPONSAVEL VARCHAR(80) null
GO

ALTER TABLE LB_LogBook DROP CONSTRAINT FK_LB_LogBook_UserCRT
GO
ALTER TABLE LB_LogBook ALTER COLUMN LB_RATRESPONSAVEL VARCHAR(80) null
GO
ALTER TABLE LB_LogBook ALTER COLUMN LB_USERNAMECAD VARCHAR(80) null
GO

ALTER TABLE LB_ACOESTOMADAS DROP CONSTRAINT FK_LB_ACOESTOMADAS_USERCRT
GO
ALTER TABLE LB_ACOESTOMADAS ALTER COLUMN ACT_RESPONSAVEL VARCHAR(80)  null
GO

ALTER TABLE agendamento alter column AG_RAT VARCHAR(80) null
go
ALTER TABLE agendamento alter column AG_RESPONSAVEL VARCHAR(80) null
go
ALTER TABLE agendamento alter column AG_USERNAME VARCHAR(80) NULL
GO

ALTER TABLE Reserva_ambientes ALTER COLUMN RAM_Responsavel VARCHAR(80) NULL
GO

ALTER TABLE Orgao ALTER COLUMN ORGA_USERIDCHEFE VARCHAR(80) NULL
GO

ALTER TABLE UserCRT DROP CONSTRAINT PK__UserCRT__0DAF0CB0
go
ALTER TABLE UserCRT alter column userid VARCHAR(80) not null
go

ALTER TABLE SCE_Usuarios ALTER COLUMN USER_LOGIN VARCHAR(80) NULL
GO



/*
	TESTA OS USUÁRIOS ANTES DE COLOCAR O "@EMBRATEL.COM.BR"

	TRECHO DE VALIDAÇÃO SOMENTE !

			SELECT * FROM Plantao WHERE PLA_USERID NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM TAREFAS_PREVISTAS WHERE PES_USERNAME NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM Historico_Eventos WHERE HE_RESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM Historico_EventosOS WHERE HEOS_RESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM Ordem_de_Servico WHERE OS_RESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			go

			SELECT * FROM SCE_Reserva WHERE RES_RESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			go

			SELECT * FROM HISTORICO_ARQUIVOS WHERE HA_USUARIO NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM Historico_datas WHERE HD_RESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM LB_LogBook WHERE LB_RATRESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			GO
			SELECT * FROM LB_LogBook WHERE LB_USERNAMECAD NOT IN (SELECT userid FROM UserCRT) -- OK SE NÃO HOUVER
			GO

			SELECT * FROM LB_ACOESTOMADAS WHERE ACT_RESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM agendamento WHERE AG_USERNAME NOT IN (SELECT userid FROM UserCRT) -- OK SE NÃO HOUVER
			GO
			SELECT * FROM agendamento WHERE AG_RESPONSAVEL NOT IN (SELECT userid FROM UserCRT)
			GO
			SELECT * FROM agendamento WHERE AG_RAT NOT IN (SELECT userid FROM UserCRT)
			GO

			SELECT * FROM SCE_Usuarios WHERE USER_LOGIN NOT IN (SELECT userid FROM UserCRT)
			GO
*/


/*
	ATUALIZA OS CAMPOS PARA FICAREM COM O EMAIL @EMBRATEL.COM.BR
*/

UPDATE EquipeEmbratel SET UserId_Gerente = LTRIM(RTRIM(LOWER(UserId_Gerente))) + '@embratel.com.br'
GO
UPDATE EquipeEmbratel SET UserId_Membro = LTRIM(RTRIM(LOWER(UserId_Membro))) + '@embratel.com.br'
GO


UPDATE Plantao SET PLA_USERID = LTRIM(RTRIM(LOWER(PLA_USERID))) + '@embratel.com.br'
GO

UPDATE TAREFAS_PREVISTAS SET PES_USERNAME = LTRIM(RTRIM(LOWER(PES_USERNAME))) + '@embratel.com.br'
GO

UPDATE Historico_Eventos SET HE_RESPONSAVEL = LTRIM(RTRIM(LOWER(HE_RESPONSAVEL))) + '@embratel.com.br'
GO

UPDATE Historico_EventosOS SET HEOS_RESPONSAVEL = LTRIM(RTRIM(LOWER(HEOS_RESPONSAVEL))) + '@embratel.com.br'
GO

UPDATE Ordem_de_Servico SET OS_RESPONSAVEL = LTRIM(RTRIM(LOWER(OS_RESPONSAVEL))) + '@embratel.com.br'
go

UPDATE SCE_Reserva SET RES_RESPONSAVEL = LTRIM(RTRIM(LOWER(RES_RESPONSAVEL))) + '@embratel.com.br'
go

UPDATE ARQUIVOS SET ARQ_RESPONSAVEL = LTRIM(RTRIM(LOWER(ARQ_RESPONSAVEL))) + '@embratel.com.br' WHERE ARQ_RESPONSAVEL IS NOT NULL
GO
UPDATE ARQUIVOS SET USERIDCADASTRO = LTRIM(RTRIM(LOWER(USERIDCADASTRO))) + '@embratel.com.br' WHERE USERIDCADASTRO IS NOT NULL
GO

UPDATE HISTORICO_ARQUIVOS SET HA_USUARIO = LTRIM(RTRIM(LOWER(HA_USUARIO))) + '@embratel.com.br'
GO

UPDATE Historico_datas SET HD_RESPONSAVEL = LTRIM(RTRIM(LOWER(HD_RESPONSAVEL))) + '@embratel.com.br'
GO

UPDATE LB_LogBook SET LB_RATRESPONSAVEL = LTRIM(RTRIM(LOWER(LB_RATRESPONSAVEL))) + '@embratel.com.br'
GO
UPDATE LB_LogBook SET LB_USERNAMECAD = LTRIM(RTRIM(LOWER(LB_USERNAMECAD))) + '@embratel.com.br'
GO

UPDATE LB_ACOESTOMADAS SET ACT_RESPONSAVEL = LTRIM(RTRIM(LOWER(ACT_RESPONSAVEL))) + '@embratel.com.br'
GO


UPDATE agendamento SET AG_USERNAME = LTRIM(RTRIM(LOWER(AG_USERNAME))) + '@embratel.com.br'
GO
UPDATE agendamento SET AG_RESPONSAVEL = LTRIM(RTRIM(LOWER(AG_RESPONSAVEL))) + '@embratel.com.br'
GO
UPDATE agendamento SET AG_RAT = LTRIM(RTRIM(LOWER(AG_RAT))) + '@embratel.com.br'
GO

UPDATE Reserva_Ambientes SET RAM_Responsavel = LTRIM(RTRIM(LOWER(RAM_Responsavel))) + '@embratel.com.br'
GO

UPDATE Orgao SET ORGA_USERIDCHEFE = LTRIM(RTRIM(LOWER(ORGA_USERIDCHEFE))) + '@embratel.com.br'
GO

UPDATE UserCRT SET userid = LTRIM(RTRIM(LOWER(userid))) + '@embratel.com.br'
GO

UPDATE SCE_Usuarios SET USER_LOGIN = LTRIM(RTRIM(LOWER(USER_LOGIN))) + '@embratel.com.br'
GO


/*
	RECRIAMOS AS CONSTRAINTS
*/

ALTER TABLE UserCRT ADD CONSTRAINT PK_USERCRT PRIMARY KEY (USERID)
GO

ALTER TABLE Plantao
	ADD CONSTRAINT FK_PLANTAO_USERCRT FOREIGN KEY (PLA_USERID)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE TAREFAS_PREVISTAS
	ADD CONSTRAINT FK_TAREFAS_PREVISTAS_USERCRT FOREIGN KEY (PES_USERNAME)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE Historico_Eventos 
	ADD CONSTRAINT FK_Historico_Eventos_UserCRT FOREIGN KEY (HE_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE Historico_EventosOS
	ADD CONSTRAINT FK_Historico_EventosOS_UserCRT FOREIGN KEY (HEOS_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE Ordem_de_Servico
	ADD CONSTRAINT FK_Ordem_de_Servico_UserCRT FOREIGN KEY (OS_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE SCE_Reserva
	ADD CONSTRAINT FK_SCE_Reserva_UserCRT FOREIGN KEY (RES_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE HISTORICO_ARQUIVOS 
	ADD CONSTRAINT FK_Historico_Arquivos_UserCRT FOREIGN KEY (HA_USUARIO)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE Historico_datas 
	ADD CONSTRAINT FK_Historico_datas_UserCRT FOREIGN KEY (HD_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE LB_LogBook
	ADD CONSTRAINT FK_LB_LogBook_RAT_UserCRT FOREIGN KEY (LB_RATRESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE LB_ACOESTOMADAS
	ADD CONSTRAINT FK_LB_ACOESTOMADAS_USERCRT FOREIGN KEY (ACT_RESPONSAVEL)
		REFERENCES UserCRT (UserID)
GO

ALTER TABLE agendamento ADD CONSTRAINT FK_Agendamento_UserCRT_RAT FOREIGN KEY (AG_RAT) REFERENCES UserCRT (Userid)
go

ALTER TABLE agendamento ADD CONSTRAINT FK_Agendamento_UserCRT_RT FOREIGN KEY (AG_RESPONSAVEL) REFERENCES UserCRT (Userid)
go


--ALTER TABLE SCE_Usuarios ADD CONSTRAINT FK_SCE_Usuarios_UserCRT FOREIGN KEY (USER_LOGIN) REFERENCES UserCRT (Userid)
--go


/*********************************************************************************************************

	OUTRAS ALTERAÇÕES PARA CORREÇÃO DE CAMPOS E/OU INDICES
***/

ALTER TABLE Orgao ALTER COLUMN ORGA_SIGLA VARCHAR(50) NOT NULL
GO

ALTER TABLE PesquisaSatisfacao ADD CONSTRAINT PK_PesquisaSatisfacao PRIMARY KEY (PSQ_ID)
GO


ALTER TABLE SCE_Movimentacao ALTER COLUMN MOV_DESPACHANTE VARCHAR(80) NULL
GO
ALTER TABLE SCE_Movimentacao ALTER COLUMN MOV_SOLICITANTE VARCHAR(80) NULL
GO


ALTER TABLE SCE_Documentacao ALTER COLUMN DOC_RESPONSAVEL VARCHAR(80) NULL
GO

ALTER TABLE SCE_Equipamentos_Controle ALTER COLUMN EQC_RESPONSAVEL VARCHAR(80) NULL
GO



--verificar se a coluna existe no Banco
--IF EXISTS(
--	SELECT *
--	FROM SYS.SYSOBJECTS SO
--	JOIN SYS.SYSCOLUMNS SC ON SC.ID = SO.ID
--	WHERE SO.XTYPE = N'U'
--	AND SO.NAME LIKE N'AGENDAMENTO%'
--	AND SC.NAME LIKE N'AG_MATRICULARESP%'
--)
--	ALTER TABLE Agendamento DROP COLUMN AG_MATRICULARESP
--go

--IF EXISTS(
--	SELECT *
--	FROM SYS.SYSOBJECTS SO
--	JOIN SYS.SYSCOLUMNS SC ON SC.ID = SO.ID
--	WHERE SO.XTYPE = N'U'
--	AND SO.NAME LIKE N'AGENDAMENTO%'
--	AND SC.NAME LIKE N'AG_NOMERESP%'
--)
--	ALTER TABLE Agendamento DROP COLUMN AG_NOMERESP
--go

--IF EXISTS(
--	SELECT *
--	FROM SYS.SYSOBJECTS SO
--	JOIN SYS.SYSCOLUMNS SC ON SC.ID = SO.ID
--	WHERE SO.XTYPE = N'U'
--	AND SO.NAME LIKE N'AGENDAMENTO%'
--	AND SC.NAME LIKE N'AG_TELEFONERESP%'
--)
--	ALTER TABLE Agendamento DROP COLUMN AG_TELEFONERESP
--go

-- Recria os campos para matricula/nome/telefone do criador da AS
ALTER TABLE Agendamento ADD AG_USERNAME_MATRICULA varchar(30)
go
ALTER TABLE Agendamento ADD AG_USERNAME_NOME varchar(100)
go
ALTER TABLE Agendamento ADD AG_USERNAME_TELEFONE varchar(30)
go



/*****
	29-05-2019
*/
DROP TABLE dbo.SCE_Equipamentos_Propriedade 
CREATE TABLE dbo.SCE_Equipamentos_Propriedade (
	ID_PROPRIEDADE CHAR(1) NOT NULL,
	NM_PROPRIEDADE VARCHAR(50) NOT NULL
)
GO
ALTER TABLE dbo.SCE_Equipamentos_Propriedade ADD CONSTRAINT PK_Equipamentos_Propriedade PRIMARY KEY (ID_PROPRIEDADE)
GO

INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('T', 'CRT Fundão - Terceiros')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('O', 'CRT Fundão - Claro - Outros')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('C', 'CRT Fundão')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('M', 'CRT Fundão - Comodato')
GO

INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('A', 'CRT Campinas - Terceiros')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('B', 'CRT Campinas - Claro - Outros')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('D', 'CRT Campinas')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('E', 'CRT Campinas - Comodato')
GO

INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('F', 'CRT Morumbi - Terceiros')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('G', 'CRT Morumbi - Claro - Outros')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('H', 'CRT Morumbi')
GO
INSERT INTO dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE, NM_PROPRIEDADE)
	VALUES ('I', 'CRT Morumbi - Comodato')
GO

CREATE INDEX IX_SCE_Equipamentos_Propriedade ON dbo.SCE_Equipamentos
	(EQ_PROPRIEDADE) 
GO

ALTER TABLE dbo.SCE_Equipamentos
	ADD CONSTRAINT FK_SCE_Equipamentos_Propriedade FOREIGN KEY (EQ_PROPRIEDADE)
		REFERENCES dbo.SCE_Equipamentos_Propriedade (ID_PROPRIEDADE)
GO




/* FIM DO SCRIPT */





/*		Executado e incluído neste script em 10/04/2019

	ALTER TABLE ARQUIVOS ALTER COLUMN ARQ_RESPONSAVEL VARCHAR(80)
	GO
	ALTER TABLE ARQUIVOS ALTER COLUMN USERIDCADASTRO VARCHAR(80)
	GO
	UPDATE ARQUIVOS SET ARQ_RESPONSAVEL = LTRIM(RTRIM(LOWER(ARQ_RESPONSAVEL))) + '@embratel.com.br' WHERE ARQ_RESPONSAVEL IS NOT NULL
	GO
	UPDATE ARQUIVOS SET USERIDCADASTRO = LTRIM(RTRIM(LOWER(USERIDCADASTRO))) + '@embratel.com.br' WHERE USERIDCADASTRO IS NOT NULL
	GO
*/
