/***

	DE - PARA de usuários

	OBS:
		LAILAJS@Embratel.com.br ->  T3LAIL

		MZMOTAV@Embratel.com.br -> T3MZEN

		FROCHAM@Embratel.com.br -> OK
***/
USE SISLAB

DECLARE @USR_DE VARCHAR(50), @USR_PARA VARCHAR(50)

SET @USR_DE = 'T3LAIL'
SET @USR_PARA = 'LAILAJS'
--SET @USR_PARA = 'T3MZEN'
--SET @USR_PARA = 'MZMOTAV'

BEGIN TRANSACTION

UPDATE EquipeEmbratel 
	SET UserId_Gerente = @USR_PARA
	WHERE UPPER(UserId_Gerente) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM EquipeEmbratel (1)', 16, 1 )
END

UPDATE EquipeEmbratel 
	SET UserId_Membro = @USR_PARA
	WHERE UPPER(UserId_Membro) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM EquipeEmbratel (2)', 16, 1 )
END

UPDATE Plantao 
	SET PLA_USERID = @USR_PARA
	WHERE UPPER(PLA_USERID) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM Plantao', 16, 1 )
END

UPDATE TAREFAS_PREVISTAS 
	SET PES_USERNAME = @USR_PARA
	WHERE UPPER(PES_USERNAME) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM TAREFAS_PREVISTAS', 16, 1 )
END

UPDATE Historico_Eventos
	SET HE_RESPONSAVEL = @USR_PARA
	WHERE UPPER(HE_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM Historico_Eventos', 16, 1 )
END

UPDATE Historico_EventosOS 
	SET HEOS_RESPONSAVEL = @USR_PARA
	WHERE UPPER(HEOS_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM Historico_EventosOS', 16, 1 )
END

UPDATE Ordem_de_Servico 
	SET OS_RESPONSAVEL = @USR_PARA
	WHERE UPPER(OS_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM Ordem_de_Servico', 16, 1 )
END

UPDATE SCE_Reserva 
	SET RES_RESPONSAVEL = @USR_PARA 
	WHERE UPPER(RES_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM SCE_Reserva', 16, 1 )
END

UPDATE ARQUIVOS 
	SET ARQ_RESPONSAVEL = @USR_PARA
	WHERE UPPER(ARQ_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM ARQUIVOS (1)', 16, 1 )
END

UPDATE ARQUIVOS 
	SET USERIDCADASTRO = @USR_PARA
	WHERE UPPER(USERIDCADASTRO) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM ARQUIVOS (2)', 16, 1 )
END

UPDATE HISTORICO_ARQUIVOS 
	SET HA_USUARIO = @USR_PARA
	WHERE UPPER(HA_USUARIO) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM HISTORICO_ARQUIVOS', 16, 1 )
END

UPDATE Historico_datas 
	SET HD_RESPONSAVEL = @USR_PARA
	WHERE UPPER(HD_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM Historico_datas', 16, 1 )
END

UPDATE LB_LogBook 
	SET LB_RATRESPONSAVEL = @USR_PARA
	WHERE UPPER(LB_RATRESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM LB_LogBook', 16, 1 )
END

UPDATE LB_LogBook 
	SET LB_USERNAMECAD = @USR_PARA
	WHERE UPPER(LB_USERNAMECAD) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM LB_LogBook', 16, 1 )
END

UPDATE LB_ACOESTOMADAS 
	SET ACT_RESPONSAVEL = @USR_PARA
	WHERE UPPER(ACT_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM LB_ACOESTOMADAS', 16, 1 )
END

UPDATE agendamento 
	SET AG_USERNAME = @USR_PARA
	WHERE UPPER(AG_USERNAME) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM agendamento (1)', 16, 1 )
END

UPDATE agendamento 
	SET AG_RESPONSAVEL = @USR_PARA
	WHERE UPPER(AG_RESPONSAVEL) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM agendamento (2)', 16, 1 )
END

UPDATE agendamento 
	SET AG_RAT = @USR_PARA
	WHERE UPPER(AG_RAT) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM agendamento (3)', 16, 1 )
END

UPDATE Reserva_Ambientes 
	SET RAM_Responsavel = @USR_PARA
	WHERE UPPER(RAM_Responsavel) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM Reserva_Ambientes', 16, 1 )
END

UPDATE Orgao 
	SET ORGA_USERIDCHEFE = @USR_PARA
	WHERE UPPER(ORGA_USERIDCHEFE) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM ORGAO', 16, 1 )
END

UPDATE SCE_Usuarios 
	SET USER_LOGIN = @USR_PARA
	WHERE UPPER(USER_LOGIN) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM SCE_Usuarios', 16, 1 )
END

DELETE FROM UserCRT
	WHERE UPPER(userid) = @USR_DE
IF @@ERROR <> 0 BEGIN
	ROLLBACK TRANSACTION
	RAISERROR( 'ERRO EM UserCRT', 16, 1 )
END

--ROLLBACK TRANSACTION
COMMIT TRANSACTION

/*
SELECT * FROM Historico_Eventos 
WHERE HE_RESPONSAVEL = 'T3LAIL'

INSERT INTO USERCRT
	SELECT * --'LAILAJS' AS USERID, NOME, CELULAR, RAMAL, MATRICULA, ORGA_ID, RT, RAT, Exibir, GQ, ID_PERFIL_SCE
	FROM UserCRT 
	WHERE USERID = 'LAILAJS'
	'T3LAIL'

INSERT INTO USERCRT
	SELECT 'T3LAIL' AS USERID, 'LAILA (T3) JORGE DE SOUSA' AS NOME, CELULAR, RAMAL, MATRICULA, ORGA_ID, RT, RAT, Exibir, GQ, ID_PERFIL_SCE
	FROM UserCRT 
	WHERE USERID = 'LAILAJS'
*/
