CREATE TABLE [dbo].[Diagramas] (
    [AG_NUMERO]  SMALLINT NOT NULL,
    [ARQ_CODARQ] INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([AG_NUMERO] ASC, [ARQ_CODARQ] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Diagramas__AG_NU__0E6E26BF] FOREIGN KEY ([AG_NUMERO]) REFERENCES [dbo].[Agendamento] ([AG_NUMERO]),
    CONSTRAINT [FK__Diagramas__ARQ_C__0D7A0286] FOREIGN KEY ([ARQ_CODARQ]) REFERENCES [dbo].[Arquivos] ([ARQ_CODARQ])
);


GO
ALTER TABLE [dbo].[Diagramas] NOCHECK CONSTRAINT [FK__Diagramas__AG_NU__0E6E26BF];


GO
ALTER TABLE [dbo].[Diagramas] NOCHECK CONSTRAINT [FK__Diagramas__ARQ_C__0D7A0286];

