CREATE TABLE [dbo].[Historico_EventosOS] (
    [HEOS_ID]          SMALLINT      IDENTITY (1, 1) NOT NULL,
    [HEOS_RESPONSAVEL] VARCHAR (20)  NULL,
    [AG_NUMERO]        SMALLINT      NULL,
    [ID_SITUACAO]      SMALLINT      NULL,
    [OS_ID]            SMALLINT      NULL,
    [HEOS_DATAINICIO]  DATETIME      NULL,
    [HEOS_DATATERMINO] SMALLDATETIME NULL,
    [HEOS_MOTIVO]      VARCHAR (255) NULL,
    CONSTRAINT [PK__Historico_Evento__5441852A] PRIMARY KEY CLUSTERED ([HEOS_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Historico__HEOS___2180FB33] FOREIGN KEY ([HEOS_RESPONSAVEL]) REFERENCES [dbo].[UserCRT] ([USERID]),
    CONSTRAINT [FK__Historico__ID_SI__208CD6FA] FOREIGN KEY ([ID_SITUACAO]) REFERENCES [dbo].[Situacoes] ([ID_SITUACAO]),
    CONSTRAINT [FK__Historico_Evento__22751F6C] FOREIGN KEY ([OS_ID], [AG_NUMERO]) REFERENCES [dbo].[Ordem_de_Servico] ([OS_ID], [AG_NUMERO])
);


GO
ALTER TABLE [dbo].[Historico_EventosOS] NOCHECK CONSTRAINT [FK__Historico__HEOS___2180FB33];


GO
ALTER TABLE [dbo].[Historico_EventosOS] NOCHECK CONSTRAINT [FK__Historico__ID_SI__208CD6FA];


GO
ALTER TABLE [dbo].[Historico_EventosOS] NOCHECK CONSTRAINT [FK__Historico_Evento__22751F6C];

