CREATE TABLE [dbo].[HISTORICO_ARQUIVOS] (
    [HA_ID]              INT           IDENTITY (1, 1) NOT NULL,
    [HA_CODARQ]          INT           NOT NULL,
    [HA_USUARIO]         VARCHAR (20)  NOT NULL,
    [HA_DATAATUALIZACAO] SMALLDATETIME NOT NULL,
    [HA_ACAO]            VARCHAR (20)  NOT NULL,
    CONSTRAINT [FK_HISTORICO_ARQUIVOS_Arquivos] FOREIGN KEY ([HA_CODARQ]) REFERENCES [dbo].[Arquivos] ([ARQ_CODARQ]),
    CONSTRAINT [FK_Historico_Arquivos_UserCRT] FOREIGN KEY ([HA_USUARIO]) REFERENCES [dbo].[UserCRT] ([USERID])
);


GO
ALTER TABLE [dbo].[HISTORICO_ARQUIVOS] NOCHECK CONSTRAINT [FK_HISTORICO_ARQUIVOS_Arquivos];


GO
ALTER TABLE [dbo].[HISTORICO_ARQUIVOS] NOCHECK CONSTRAINT [FK_Historico_Arquivos_UserCRT];

