CREATE TABLE [dbo].[LB_ACOESTOMADAS] (
    [ACT_ID]            INT           IDENTITY (1, 1) NOT NULL,
    [ACT_LB]            SMALLINT      NOT NULL,
    [ACT_DESCRICAO]     VARCHAR (255) NULL,
    [ACT_EXECUTANTE]    VARCHAR (200) NULL,
    [ACT_PRAZO]         SMALLDATETIME NULL,
    [ACT_DATACONCLUSAO] SMALLDATETIME NULL,
    [ACT_EFICACIA]      TINYINT       NULL,
    [ACT_OBS]           TEXT          NULL,
    [ACT_TIPOACAO]      INT           NOT NULL,
    [ACT_RESPONSAVEL]   VARCHAR (20)  NULL,
    CONSTRAINT [PK_LB_ACOESTOMADAS] PRIMARY KEY CLUSTERED ([ACT_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_LB_ACOESTOMADAS_LB_LogBook] FOREIGN KEY ([ACT_LB]) REFERENCES [dbo].[LB_LogBook] ([LB_ID]),
    CONSTRAINT [FK_LB_ACOESTOMADAS_LB_TIPOACAOTOMADA] FOREIGN KEY ([ACT_TIPOACAO]) REFERENCES [dbo].[LB_TIPOACAOTOMADA] ([TAT_ID]),
    CONSTRAINT [FK_LB_ACOESTOMADAS_USERCRT] FOREIGN KEY ([ACT_RESPONSAVEL]) REFERENCES [dbo].[UserCRT] ([USERID])
);


GO
ALTER TABLE [dbo].[LB_ACOESTOMADAS] NOCHECK CONSTRAINT [FK_LB_ACOESTOMADAS_LB_LogBook];


GO
ALTER TABLE [dbo].[LB_ACOESTOMADAS] NOCHECK CONSTRAINT [FK_LB_ACOESTOMADAS_LB_TIPOACAOTOMADA];


GO
ALTER TABLE [dbo].[LB_ACOESTOMADAS] NOCHECK CONSTRAINT [FK_LB_ACOESTOMADAS_USERCRT];

