CREATE TABLE [dbo].[LB_ACOESTOMADAS_ARQUIVOS] (
    [ACA_ID]               INT            IDENTITY (1, 1) NOT NULL,
    [ACT_ID]               INT            NOT NULL,
    [LB_ID]                SMALLINT       NOT NULL,
    [ACA_LINK]             VARCHAR (5000) NOT NULL,
    [ACA_USUARIOCADASTROU] VARCHAR (20)   NULL,
    [ACA_DATACADASTRO]     DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([ACA_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_LB_ACOESTOMADAS_LB_ACOESTOMADAS_ARQUIVOS] FOREIGN KEY ([ACT_ID]) REFERENCES [dbo].[LB_ACOESTOMADAS] ([ACT_ID]),
    CONSTRAINT [FK_LB_LOGBOOK_LB_ACOESTOMADAS_ARQUIVOS] FOREIGN KEY ([LB_ID]) REFERENCES [dbo].[LB_LogBook] ([LB_ID])
);


GO
ALTER TABLE [dbo].[LB_ACOESTOMADAS_ARQUIVOS] NOCHECK CONSTRAINT [FK_LB_ACOESTOMADAS_LB_ACOESTOMADAS_ARQUIVOS];


GO
ALTER TABLE [dbo].[LB_ACOESTOMADAS_ARQUIVOS] NOCHECK CONSTRAINT [FK_LB_LOGBOOK_LB_ACOESTOMADAS_ARQUIVOS];

