CREATE TABLE [dbo].[LB_LogBook] (
    [LB_ID]                SMALLINT      IDENTITY (1, 1) NOT NULL,
    [LBTO_ID]              SMALLINT      NULL,
    [LB_DATAHORACAD]       SMALLDATETIME NULL,
    [LB_USERNAMECAD]       VARCHAR (10)  NULL,
    [LB_IPCAD]             VARCHAR (20)  NULL,
    [LB_DESCRICAO]         TEXT          NULL,
    [LB_OBSERVACAO]        TEXT          NULL,
    [LB_PROVIDENCIAS]      TEXT          NULL,
    [LB_CONCLUIDO]         BIT           CONSTRAINT [DF_LB_LogBook_LB_CONCLUIDO] DEFAULT ((0)) NOT NULL,
    [LB_CONCLUIDOGQ]       BIT           CONSTRAINT [DF_LB_LogBook_LB_CONCLUIDOGQ] DEFAULT ((0)) NOT NULL,
    [LB_DATAHORAOCO]       SMALLDATETIME NULL,
    [LB_PRAZO]             SMALLINT      NULL,
    [LB_RESPEXEC]          VARCHAR (50)  NULL,
    [LB_EXECUTOR]          TEXT          NULL,
    [LB_OBSERVACOESGQ]     TEXT          NULL,
    [LB_OBSERVACOESRES]    TEXT          NULL,
    [LB_PENDENCIAS]        TEXT          NULL,
    [LB_ANALISEGQ]         TEXT          NULL,
    [LB_DOCASSOCIADO]      TEXT          NULL,
    [LB_REQUISITONORMA]    TEXT          NULL,
    [LB_CRITICIDADE]       TINYINT       CONSTRAINT [DF_LB_LogBook_LB_CRITICIDADE] DEFAULT ((1)) NULL,
    [LB_OPM]               BIT           CONSTRAINT [DF_LB_LogBook_LB_OPM] DEFAULT ((0)) NOT NULL,
    [LB_RATRESPONSAVEL]    VARCHAR (20)  NULL,
    [LB_DATAHORACONCLUSAO] SMALLDATETIME NULL,
    CONSTRAINT [PK__LB_LogBook__173876EA] PRIMARY KEY CLUSTERED ([LB_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__LB_LogBoo__LBTO___73BA3083] FOREIGN KEY ([LBTO_ID]) REFERENCES [dbo].[LB_TipoOcorrencia] ([LBTO_ID]),
    CONSTRAINT [FK_LB_LogBook_UserCRT] FOREIGN KEY ([LB_RATRESPONSAVEL]) REFERENCES [dbo].[UserCRT] ([USERID])
);


GO
ALTER TABLE [dbo].[LB_LogBook] NOCHECK CONSTRAINT [FK__LB_LogBoo__LBTO___73BA3083];


GO
ALTER TABLE [dbo].[LB_LogBook] NOCHECK CONSTRAINT [FK_LB_LogBook_UserCRT];

