CREATE TABLE [dbo].[Plantao] (
    [PLA_CODNOTICIA]   INT            IDENTITY (1, 1) NOT NULL,
    [PLA_TITNOTICIA]   NVARCHAR (510) NULL,
    [PLA_DATAINICIO]   SMALLDATETIME  NULL,
    [PLA_DATATERMINO]  SMALLDATETIME  NULL,
    [PLA_USERID]       VARCHAR (20)   NULL,
    [PLA_DATACADASTRO] SMALLDATETIME  NULL,
    [PLA_LINK]         VARCHAR (255)  NULL,
    CONSTRAINT [PK__Plantao__412EB0B6] PRIMARY KEY CLUSTERED ([PLA_CODNOTICIA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Plantao__PLA_USE__0F624AF8] FOREIGN KEY ([PLA_USERID]) REFERENCES [dbo].[UserCRT] ([USERID])
);


GO
ALTER TABLE [dbo].[Plantao] NOCHECK CONSTRAINT [FK__Plantao__PLA_USE__0F624AF8];

