CREATE TABLE [dbo].[SCE_Passagem_Carga] (
    [EQ_ID]               INT      NOT NULL,
    [AG_NUMERO_ORIG]      SMALLINT NOT NULL,
    [AG_NUMERO_DEST]      SMALLINT NOT NULL,
    [PAS_DATAPASSAGEM]    DATETIME DEFAULT (getdate()) NULL,
    [PAS_DATARECEBIMENTO] DATETIME NULL,
    [PAS_APROVADO]        BIT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SCE_Passagem_Carga] PRIMARY KEY CLUSTERED ([EQ_ID] ASC, [AG_NUMERO_ORIG] ASC, [AG_NUMERO_DEST] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SCE_Passagem_Carga_AG_NUMERO_DEST] FOREIGN KEY ([AG_NUMERO_DEST]) REFERENCES [dbo].[Agendamento] ([AG_NUMERO]),
    CONSTRAINT [FK_SCE_Passagem_Carga_AG_NUMERO_ORIG] FOREIGN KEY ([AG_NUMERO_ORIG]) REFERENCES [dbo].[Agendamento] ([AG_NUMERO]),
    CONSTRAINT [FK_SCE_Passagem_Carga_EQ_ID] FOREIGN KEY ([EQ_ID]) REFERENCES [dbo].[SCE_Equipamentos] ([EQ_ID])
);


GO
ALTER TABLE [dbo].[SCE_Passagem_Carga] NOCHECK CONSTRAINT [FK_SCE_Passagem_Carga_AG_NUMERO_DEST];


GO
ALTER TABLE [dbo].[SCE_Passagem_Carga] NOCHECK CONSTRAINT [FK_SCE_Passagem_Carga_AG_NUMERO_ORIG];


GO
ALTER TABLE [dbo].[SCE_Passagem_Carga] NOCHECK CONSTRAINT [FK_SCE_Passagem_Carga_EQ_ID];

