CREATE TABLE [dbo].[SCE_Equipamentos] (
    [EQ_ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [EQ_CODIGOBARRAS]         VARCHAR (20)  NULL,
    [EQ_NUMEROSERIE]          VARCHAR (255) NULL,
    [EQ_LOCALIZACAO]          VARCHAR (255) NULL,
    [MOD_ID]                  INT           NULL,
    [EQ_OBS]                  TEXT          NULL,
    [STATUS]                  TINYINT       CONSTRAINT [DF_SCE_Equipamentos_STATUS] DEFAULT ((0)) NOT NULL,
    [EQ_OPER_DELTA]           VARCHAR (50)  CONSTRAINT [DF_SCE_Equipamentos_EQ_OPER_DELTA] DEFAULT ('24 +/- 6°C') NULL,
    [EQ_OPER_UMIDADE]         VARCHAR (50)  CONSTRAINT [DF_SCE_Equipamentos_EQ_OPER_UMIDADE] DEFAULT ('40 A 70% UR') NULL,
    [EQ_OPER_WARMUP]          VARCHAR (50)  CONSTRAINT [DF_SCE_Equipamentos_EQ_OPER_WARMUP] DEFAULT ('N/A') NULL,
    [EQ_ARMA_DELTA]           VARCHAR (50)  CONSTRAINT [DF_SCE_Equipamentos_EQ_ARMA_DELTA] DEFAULT ('10 A 35°C') NULL,
    [EQ_ARMA_UMIDADE]         VARCHAR (50)  CONSTRAINT [DF_SCE_Equipamentos_EQ_ARMA_UMIDADE] DEFAULT ('20 A 80% UR') NULL,
    [EQ_MANUT_PREVENTIVA]     TEXT          NULL,
    [EQ_INSTRUMENTAL]         BIT           CONSTRAINT [DF_SCE_Equipamentos_EQ_INSTRUMENTAL] DEFAULT ((0)) NOT NULL,
    [EQ_PROPRIEDADE]          CHAR (1)      CONSTRAINT [DF_SCE_Equipamentos_EQ_PROPRIEDADE] DEFAULT ('C') NOT NULL,
    [EQ_CONFORME]             BIT           CONSTRAINT [DF_SCE_Equipamentos_EQ_CONFORME] DEFAULT ((1)) NOT NULL,
    [EQ_DT_ULT_INVENTARIO]    DATETIME      NULL,
    [EQ_FREQ_CALIBRACAO]      INT           NULL,
    [EQ_CODIGOBARRASANTERIOR] VARCHAR (20)  NULL,
    CONSTRAINT [PK_SCE_Equipamentos] PRIMARY KEY NONCLUSTERED ([EQ_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SCE_Equipamentos_SCE_Modelos] FOREIGN KEY ([MOD_ID]) REFERENCES [dbo].[SCE_Modelos] ([MOD_ID])
);


GO
ALTER TABLE [dbo].[SCE_Equipamentos] NOCHECK CONSTRAINT [FK_SCE_Equipamentos_SCE_Modelos];


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SCE_EQ_CODIGOBARRAS]
    ON [dbo].[SCE_Equipamentos]([EQ_CODIGOBARRAS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_SCE_Equipamentos_MOD_ID]
    ON [dbo].[SCE_Equipamentos]([MOD_ID] ASC) WITH (FILLFACTOR = 90);

