CREATE TABLE [dbo].[SituacaoArquivo] (
    [SAR_CODSITARQUIVO] INT            NOT NULL,
    [SAR_SITARQUIVO]    NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([SAR_CODSITARQUIVO] ASC) WITH (FILLFACTOR = 90)
);

