CREATE TABLE [dbo].[TAREFAS_PREVISTAS] (
    [TAREFA_ID]      SMALLINT       NOT NULL,
    [TP_ID]          INT            IDENTITY (1, 1) NOT NULL,
    [TP_DATAINICIAL] SMALLDATETIME  NOT NULL,
    [TP_DATAFINAL]   SMALLDATETIME  NOT NULL,
    [TP_OBSERVACAO]  VARCHAR (8000) NULL,
    [TAREFA_TIPO]    BIT            NOT NULL,
    [PES_USERNAME]   VARCHAR (20)   NULL,
    CONSTRAINT [PK__TAREFAS_PREVISTA__532343BF] PRIMARY KEY CLUSTERED ([TP_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TAREFAS_PREVISTAS_TAREFAS] FOREIGN KEY ([TAREFA_ID]) REFERENCES [dbo].[TAREFAS] ([TAR_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_TAREFAS_PREVISTAS_UserCRT] FOREIGN KEY ([PES_USERNAME]) REFERENCES [dbo].[UserCRT] ([USERID])
);


GO
ALTER TABLE [dbo].[TAREFAS_PREVISTAS] NOCHECK CONSTRAINT [FK_TAREFAS_PREVISTAS_TAREFAS];


GO
ALTER TABLE [dbo].[TAREFAS_PREVISTAS] NOCHECK CONSTRAINT [FK_TAREFAS_PREVISTAS_UserCRT];


GO
CREATE TRIGGER [dbo].[trInsUpdTAREFAS_PREVISTAS] ON [dbo].[TAREFAS_PREVISTAS] 
FOR INSERT, UPDATE
AS

DECLARE @tot1 INT, @tot2 INT, @tot3 INT

SELECT @tot1 = COUNT(*) FROM TAREFAS_PREVISTAS
SELECT @tot2 = COUNT(*)
FROM TAREFAS_PREVISTAS AS I 
INNER JOIN TAREFAS AS T ON I.TAREFA_ID=T.TAR_ID
WHERE I.TAREFA_TIPO=1
SELECT @tot3 = COUNT(*)
FROM TAREFAS_PREVISTAS AS I 
INNER JOIN AGENDAMENTO AS A ON I.TAREFA_ID=A.AG_NUMERO
WHERE I.TAREFA_TIPO=0
IF @tot1 - (@tot2+@tot3) > 0
BEGIN
	RAISERROR 30002 'ERRO'
	ROLLBACK TRANSACTION
END

GO
DISABLE TRIGGER [dbo].[trInsUpdTAREFAS_PREVISTAS]
    ON [dbo].[TAREFAS_PREVISTAS];

