CREATE TABLE [dbo].[TECNOLOGIA] (
    [TEC_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [TEC_NOME] VARCHAR (50) NULL,
    [AT_ID]    SMALLINT     NULL,
    CONSTRAINT [PK_TECNOLOGIA] PRIMARY KEY CLUSTERED ([TEC_ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Tecnologia_Area_Tecnologica] FOREIGN KEY ([AT_ID]) REFERENCES [dbo].[Area_Tecnologica] ([AT_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[TECNOLOGIA] NOCHECK CONSTRAINT [FK_Tecnologia_Area_Tecnologica];

