CREATE TABLE [dbo].[TipoArquivo] (
    [TAR_CODTIPOARQUIVO] INT            IDENTITY (1, 1) NOT NULL,
    [TAR_TIPOARQUIVO]    NVARCHAR (240) NULL,
    [TAR_CONFIDENCIAL]   BIT            CONSTRAINT [DF_TipoArquivo_TAR_CONFIDENCIAL] DEFAULT ((0)) NOT NULL,
    [TAR_SENHA]          NVARCHAR (15)  NULL,
    [TAR_DocQual]        BIT            CONSTRAINT [DF_TipoArquivo_TAR_DocQual] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__TipoArquivo__300424B4] PRIMARY KEY CLUSTERED ([TAR_CODTIPOARQUIVO] ASC) WITH (FILLFACTOR = 90)
);

