CREATE TABLE [dbo].[Tipo_Atividade] (
    [TA_ID]         SMALLINT      IDENTITY (1, 1) NOT NULL,
    [TA_DESCRICAO]  VARCHAR (200) NULL,
    [TA_FLAGTABELA] TINYINT       NULL,
    CONSTRAINT [PK__Tipo_Atividade__0F975522] PRIMARY KEY CLUSTERED ([TA_ID] ASC) WITH (FILLFACTOR = 90)
);

