
CREATE TABLE dbo.CentroReferencia (
	ID_CRT TINYINT NOT NULL,
	NM_CRT VARCHAR(100) NOT NULL,
	SIGLA_CRT VARCHAR(10)
)
GO

ALTER TABLE dbo.CentroReferencia ADD CONSTRAINT PK_CentroReferencia PRIMARY KEY (ID_CRT)
GO

INSERT INTO CentroReferencia (ID_CRT, NM_CRT, SIGLA_CRT) VALUES (1, 'CRT FUNDÃO', 'CRTFUN')
GO
INSERT INTO CentroReferencia (ID_CRT, NM_CRT, SIGLA_CRT) VALUES (2, 'CRT MORUMBI', 'CRTMBI')
GO
INSERT INTO CentroReferencia (ID_CRT, NM_CRT, SIGLA_CRT) VALUES (3, 'CRT CAMPINAS', 'CRTCPS')
GO



ALTER TABLE dbo.Ambientes ADD AMB_MODULO TINYINT
go

ALTER TABLE dbo.Ambientes ADD ID_CRT TINYINT
go

ALTER TABLE dbo.Ambientes
	ADD CONSTRAINT FK_Ambientes_CentroReferencia FOREIGN KEY (ID_CRT)
		REFERENCES dbo.CentroReferencia (ID_CRT)
GO


UPDATE AMBIENTES SET AMB_MODULO = 1, ID_CRT = 1
GO


ALTER TABLE dbo.SCE_Equipamentos ADD AMB_ID INT
go
ALTER TABLE dbo.SCE_Equipamentos
	ADD CONSTRAINT FK_SCE_Equipamentos_Ambientes FOREIGN KEY (AMB_ID)
		REFERENCES dbo.Ambientes (AMB_ID)
GO


ALTER TABLE UserCRT ADD ID_CRT TINYINT
go
ALTER TABLE dbo.UserCRT
	ADD CONSTRAINT FK_UserCRT_CentroReferencia FOREIGN KEY (ID_CRT)
		REFERENCES dbo.CentroReferencia (ID_CRT)
GO

