<%
'== Monta a tela do sistema =====================================================
Sub MostraHeader()

%>
<left>
<map name="teste">
<area alt="" coords="3,3,250,68" href="http://ntspo905/sislab1/index.asp">
<area alt="" coords="637,4,756,65" href="http://pegasus/">
</map>
<img src="../img/barra_crt2.jpg" border=0 usemap="#teste" id="figura">
</left>
<%
End Sub
Sub MostraHeader1_1()
	%>
<HTML>
<HEAD>
<meta http-equiv="pragma" content="no-cache">
	<STYLE TYPE="text/css">
	<!--
	A:link {color:#000060;}
	A:visited {color:#333360;}
	A:hover {color:#0000FF;}
	A:active {color:black;}
	A {text-decoration:none}
	-->
	</STYLE>



<TITLE>Site da Controladoria</TITLE>

<%
End Sub

Sub MostraFooter()
	%>
	<br>
	</BODY>
	</HTML>
	<%
End Sub
%>