<%
'--------- CONSTANTE DE USUARIOS ---------------
Dim RAT_Username(6), RAT_Nome(6), RESP_Exec_Username(6), RESP_Exec_Nome(6)
Dim GQ_Username(6), GQ_Nome(6), RAT_MEMBROS, RESP_MEMBROS, GQ_MEMBROS

'-------------- OS RAT'S DO SISTEMA --------------------
RAT_Username(0) = "VIDAL"
RAT_Nome(0) = "Walderson João Rodrigues Vidal"
RAT_Username(1) = "CRCUNHA" 
RAT_Nome(1) = "Carlos Ribeiro da Cunha"
RAT_Username(2) = "ANETTO"
RAT_Nome(2) = "Antonio Carlos Araújo Netto"
RAT_Username(3) = "ANTUNES"
RAT_Nome(3) = "Maria de Fátima Antunes Teixeira"
RAT_MEMBROS = 3

'------------- OS RESPONSAVEIS POR EXECUCAO DO SISTEMA ---------

RESP_EXEC_Username(0) = "ANETTO"
RESP_EXEC_Nome(0) = "Antonio Carlos Araújo Netto"
RESP_EXEC_Username(1) = "ANTUNES"
RESP_EXEC_Nome(1) = "Maria de Fátima Antunes Teixeira"
RESP_EXEC_Username(2) = "CRCUNHA" 
RESP_EXEC_Nome(2) = "Carlos Ribeiro da Cunha"
RESP_EXEC_Username(3) = "VIDAL"
RESP_EXEC_Nome(3) = "Walderson João Rodrigues Vidal"
RESP_EXEC_Username(4) = "JOSESP"
RESP_EXEC_Nome(4) = "José Silva Paula Junior"
RESP_MEMBROS = 4
'------------- O GERENTE DE QUALIDADE DO SISTEMA ---------

GQ_Username(0) = "VIDAL"
GQ_Nome(0) = "Walderson João Rodrigues Vidal"
GQ_Username(1) = "ANETTO"
GQ_Nome(1) = "Antonio Carlos Araújo Netto"
GQ_MEMBROS = 1
%>